### ISSUE TITLE
Failed to connect to i3: errno 111 (Connection refused)

### ISSUE THREAD

**Issue by CarlosMChica** [jaagr/polybar#1004]
Hi,

polybar is failing to display i3 workspaces and shows the following error on start-up:

`error: Disabling module "i3" (reason: Failed to connect to i3: errno 111 (Connection refused))`

I'm using `polybar-git` package from Yaourt in ArchLinux. I also tried installing `polybar` package just in case there was something wrong in the master branch, but the result is the same. 

I'm actually not sure if this is an issue related to i3 or polybar, but I thought I'd open an issue to see if someone can show me some light.

Thanks.

**Comment by patrick96** [comment]
Seems like the error is thrown [here](https://github.com/jaagr/i3ipcpp/blob/a6aa7a19786bdf7b96a02900510b3b3c325c8bdf/src/ipc-util.cpp#L68).
Polybar can't connect to the i3 socket, this is most likely not a polybar issue, since the i3 socket does not accept the connection. It's possible that it has something to do with your i3 setup. Try to use the default i3 config

**Comment by CarlosMChica** [comment]
I'm unsure what was causing it, but it has gone away now, closing this issue.
