### ISSUE TITLE
Can't get Unicode characters to work

### ISSUE THREAD

**Issue by fbrinker** [jaagr/polybar#1050]
Hello everyone, 

I know this question is asked many times on the web, but i can't find any working solution... I guess i miss some stupid details... :/

**My setup**
* Manjaro Deepin (Arch) with alternatively installed 
* i3-gaps and 
* polybar 3.1.0
* FontsAwesome 5 (ttf) [also tried FontAwesome 4, material design icons etc]

**The polybar config**
```
font-0 = fixed:pixelsize=10;1
font-1 = "Font Awesome 5 Free:style=Regular:pixelsize=12;2"
font-2 = "Font Awesome 5 Free:style=Solid:pixelsize=12;2"
font-3 = "Font Awesome 5 Brands:style=Regular:pixelsize=12;2"
```

**Polybar startup with -l info**
```
* Loaded font "fixed:pixelsize=10" (name=Noto Sans, offset=1, file=/usr/share/fonts/noto/NotoSans-Regular.ttc)
* Loaded font "Font Awesome 5 Free:style=Regular:pixelsize=12" (name=Font Awesome 5 Free, offset=2, file=/usr/share/fonts/TTF/fa-regular-400.ttf)
* Loaded font "Font Awesome 5 Free:style=Solid:pixelsize=12" (name=Font Awesome 5 Free, offset=2, file=/usr/share/fonts/TTF/fa-solid-900.ttf)
* Loaded font "Font Awesome 5 Brands:style=Regular:pixelsize=12" (name=Font Awesome 5 Brands, offset=2, file=/usr/share/fonts/TTF/fa-brands-400.ttf)
```

I've tried to insert multiple unicode chars in my config / labels. At last, i took a character from the Noto Sans font. The crazy thing is, my terminal displays the character correctly when warning me about the drop (so it is a normal utf char):
```
warn: Dropping unmatched character 🡆 (U+1f846)
```

**fc-match works also fine**
```
➜  ~ fc-match "Font Awesome 5 Free:style=Regular:pixelsize=12;2"
fa-regular-400.ttf: "Font Awesome 5 Free" "Regular"
```

**The confusing fact**
To insert the special symbols, I use gucharmap. I can see all the symbols in the normal view, but an irritating thing is that i can't see any symbols when activating the option View -> Show only glyphs in gucharmap (doesn't show an symbols for any font).
I assume that could be the problem, but i have no idea what that's about.

Any ideas? :(

**Comment by patrick96** [comment]
You're so very close. The problem is that when `Show only glyphs ...` is selected and the icon doesn't appear, that means that the selected font does not provide this glyph. You will need to find a font that does and use that font in polybar. You have a font installed that provides the `🡆 (U+1f846)` glyph, because your terminal prints it, however you have not specified that font in the polybar config. You can figure out the font a symbol comes from, by deselecting `Show only glyphs ...` and holding right click on the icon.

**Comment by fbrinker** [comment]
Oh wow... so I just didn't understand gucharmap... now it works. Thank you! :)

**Comment by Rapiz1** [comment]
No. You did not figure out this problem.
I had the same problem with you and I found something else.
When you check out the character using gucharmap, it actually displays according to all styles of this font. For example, if a character comes from Font Awesome Free 5 Solid, you can see it in Font Awesome Free 5. But if you turn on the 'Show only glyph from this font', you will find that it will disappear. This is because 'Font Awesome Free 5' refers to the regular version, which is 'Font Awesome Free Regular' but 'Font Awesome Free 5 Solid' provides the character you need.
So adding 'Font Awesome Free 5 Solid' to you font section in polybar config should solve this problem.
