### ISSUE TITLE
xbacklight stops working after removing xf86-video-intel

### ISSUE THREAD

**Issue by alexozer** [jaagr/polybar#1092]
Hi,

It's now advised for Arch users to not install `xf86-video-intel` as it's mostly not necessary anymore apparently. After doing so, however, the xbacklight section of my polybar has stopped showing up. It's strange because `/sys/class/backlight/intel_backlight/backlight` still updates fine.

[Here](https://gist.github.com/fce5a1e08c6b9dbd11a570583b1fd59a
)'s my config.

**Comment by x70b1** [comment]
You mean this section: [wiki.archlinux.org](https://wiki.archlinux.org/index.php/backlight#xbacklight)

You need the other module: `internal/backlight` not `internal/xbacklight`.
Unfortunately there is a header in the polybar-wiki: `This module is deprecated`

**Comment by alexozer** [comment]
Hm. That didn't seem to work either, had some problem with displaying the
incorrect brightness. Although I haven't investigated it much because I'm
back on the other driver now for other reasons.

**Comment by x70b1** [comment]
Sounds like it's a problem somewhere else.
But if you don't use it now, you can probably close the issue.

**Comment by patrick96** [comment]
I have removed the deprecation warning from the `backlight` module page, it should work perfectly fine, as long as the files in `/sys/class/backlight` are properly updated.

Where does it say to not install `xf86-video-intel`? I have not seen that before and if the module stops working w/o the driver, the obvious solution seems to be to reinstall the driver.

**Comment by alexozer** [comment]
> Where does it say to not install xf86-video-intel?

On the [Intel graphics archwiki page](https://wiki.archlinux.org/index.php/Intel_graphics), here:

> ... install the xf86-video-intel package. (Often not recommended, see note below.)

I ended up needing to reinstall xf66-video-intel anyhow because of performance issues, but if you read some of the pages linked from that entry in the Archwiki you'll see some people attesting that xf86-video-intel shouldn't be used anymore.

**Comment by x70b1** [comment]
@patrick96 

Ah, sorry. That wasn't the correct link. Look at this: [Intel graphics](https://wiki.archlinux.org/index.php/intel_graphics#Installation).

They suggest not to install the `xf86-video-intel`. But this means that [xorg-xbacklight](https://wiki.archlinux.org/index.php/backlight#xbacklight) cannot be used. Look at the note section. Without the Intel driver there is also no `xbacklight` command. That means you need a replacement for this.

These dependencies between Intel drivers and xbacklight are very high. Therefore it would be nice to continue the support for the `backlight` module. I guess it doesn't take much time to maintain. It's already finished code. As I understand it, the `xbacklight` module needs the Intel driver to work because it does not use the `/sys/class/backlight` path?
