### ISSUE TITLE
[request] different ramp-volume and bar-volume cursors

### ISSUE THREAD

**Issue by gpakosz** [jaagr/polybar#1093]
Hello,

Would it be possible, and would be make sense to have different cursors for `ramp-volume` and `bar-volume`? Typically `ramp-volume` would use `cursor-click` while bar-volume would use `cursor-scroll`.

What do you think?

**Comment by NBonaparte** [comment]
Currently the cursors are mapped to whatever action they are named (click and scroll), with the click cursor having priority.  Since the volume module has both scroll and click actions throughout the module, the click cursor would be shown by default.

I don't think having different cursors for the ramp and bar would be helpful, because it would contradict this order of precedence.
