### ISSUE TITLE
Provide release archives including submodules

### ISSUE THREAD

**Issue by michitux** [jaagr/polybar#1120]
I am currently trying to package polybar for postmarketOS (see postmarketOS/pmbootstrap#1343). For this, it would be much easier if the git submodules were included in the released archives (or more precisely, if you could provide custom release archives with submodules included instead of the automatically generated ones). This would allow to have a single source archive instead of requiring either several archives (whose versions need to be updated on every release) or git. Packaging both libraries separately as proposed in #1054 would be the other option, if I have the choice I would prefer the single archive and package though to keep things simple unless polybar will be modified to support having i3ipcpp and xpp installed in the system without requiring additional patches.

**Comment by patrick96** [comment]
What is keeping you from creating those archives yourself?
Also the problem with those archives is, that you don't get things like the fix for #1090 (where you have to checkout a newer submodule commit during the build process) in them. And also, what's wrong with git?

I'm not sure if the ability to build with xpp and i3ipcpp packages installed will make it into polybar, because dealing with dependencies can be hell already, and this adds just another way for dependencies to mismatch. But if it made it into polybar, you'd also have to maintain and update those two packages separately (which is more work than just pulling the submodules as tarballs).

**Comment by michitux** [comment]
If I create those archives myself, I need to host them somewhere and it is not clear to me where this should be. I could create my own GitHub repo and host them as releases there. However, this just feels wrong to me as I think these release files belong into this repo and not some random repo in my GitHub account. Alpine Linux seems to have some infrastructure for this but I don't know yet if they would be interested or if this will be only packaged in postmarketOS.

A fix for #1090 could have been to just release a minor bug fix release.

There is nothing wrong with git (and this is also what I have used so far), it's just that it is a lot more complex than a simple archive download. If you think this is the way to go feel free to close this issue.

**Comment by patrick96** [comment]
Ah I see, the structure is similar to the AUR where they only host the build script and not like launchpad where they also store all the sources.

Right now we don't have a system in place that allows us to backport bugfixes without adding all other commits to a release as well. I think, right now you should stick with using git, we may revisit adding full source tarballs once we figure out a proper release process. I appreciate the effort, feel free to open a PR to add your new package to the README once it gets into the repo

**Comment by patrick96** [comment]
BTW we now provide a `polybar.tar` for each new release which contains all the files necessary to build polybar.
