### ISSUE TITLE
Doesn't work with dwm.

### ISSUE THREAD

**Issue by Endoxx** [jaagr/polybar#1132]
If i launch it with xinit it launches but isn't useable and if i try launching it with dmenu it obstructs my wallpaper and same as before not useable i have to force kill it to continue using my PC.

**Comment by patrick96** [comment]
Did you try to set `override-redirect = true`?

**Comment by NBonaparte** [comment]
What do you mean by "isn't usable"?

**Comment by Endoxx** [comment]
by isn't usable i mean i can't use any of my dwm shortcuts anymore i pretty much stuck with the bar until i force close it.

**Comment by patrick96** [comment]
That's probably because you didn't fork it to the background and whatever should run after polybar in your xinit, only runs after the polybar process has finished

**Comment by Endoxx** [comment]
it is working now with  override-redirect = true if i start it with rofi bur if i start it with xinit its my shortcuts are unusable again.

**Comment by patrick96** [comment]
The xworkspace doesn't work on dwm, because it doesn't support `_NET_CURRENT_DESKTOP` by default, there is a [patch](https://dwm.suckless.org/patches/ewmhtags/) that even specifically mentions polybar's xworkspace module.

The polybar window is above the other window because dwm doesn't know that it needs to reserve space for polybar. You need to configure dwm to have a smaller area where it can put windows, I think you'll need to edit `dwm.c` for this.

**Comment by Endoxx** [comment]
Alright thanks i'll try your suggestions, I hope that everything is solved after this.

And i'll close the issue here, thanks again for the help.
