### ISSUE TITLE
Polybar margin

### ISSUE THREAD

**Issue by zemmsoares** [jaagr/polybar#1174]
I'm currently using 2 Bars (polybar top & polybar top-second)
soo as you can see on the screen3 the terminal is above the bars
i'm looking to make a margin soo i can allways see the bars..
i think it's override-redirect = true , but it's not working

![screen1](https://user-images.githubusercontent.com/38134965/38882198-171b97d8-4259-11e8-9492-c730a867b622.png)
![screen2](https://user-images.githubusercontent.com/38134965/38882207-19c675a2-4259-11e8-93ca-065c066ce44f.png)
![screen3](https://user-images.githubusercontent.com/38134965/38882210-1cdb74c2-4259-11e8-832a-26a80cf19c05.png)

**Comment by zemmsoares** [comment]
I3-gaps

**Comment by patrick96** [comment]
`override-redirect = true` will force the WM to not configure the bar windows, this can be helpful but causes i3 (and others) to not automatically allocate space for the bars. Since you are using i3-gaps, you can increase `gaps outer` until there is enough space for the bars. This will cause gaps to appear on all sides, I don't know, if it's possible to only specify gaps in a certain direction.

**Comment by zemmsoares** [comment]
if it's possible to only specify gaps in a certain direction.
That was my first idea but i don't think that's possible.
will try to increase gaps, but since i'm on a 12" laptop not going to be easy :)
thanks!

**Comment by NBonaparte** [comment]
Another way you could fix this is by creating the bar to be 100% width (covers the whole monitor length), but add a transparent border (#00000000) to create the illusion of a floating bar.

**Comment by patrick96** [comment]
I'm going to close this, as this is a limitation of the WM and not polybar
