### ISSUE TITLE
i3 - Show occupied workspaces

### ISSUE THREAD

**Issue by mpcsh** [jaagr/polybar#1175]
I just switched from bspwm to i3-gaps. In both bspwm and i3bar, the focused workspace can be shown as well as any occupied workspaces. This feature doesn't seem possible with the i3 module in polybar. I've also tried using the xworkspaces module, but the label-unfocused-* options don't seem to do anything. I'm happy to contribute a fix but I wouldn't know where to start!

**Comment by mpcsh** [comment]
Sorry, just edited my post - I was using `label-unfocused` to no avail. When I use it with the `i3` module type, it shows the correct workspaces, but ignores all formatting rules (underline, background, etc). When I use it with the `xworkspaces` module, it has no effect.

**Comment by NBonaparte** [comment]
It's not implemented in xworkspaces modules yet (see the wiki page).

What does your i3 module config look like?

**Comment by mpcsh** [comment]
D'oh. I was using `label-active` and `label-unfocused` instead of `label-focused` and `label-unfocused`. I feel like that should throw an error since the `i3` module doesn't define `label-active` but oh well.

**Comment by patrick96** [comment]
Polybar doesn't complain when a key is not used by a module. That's because you could for example define `padding = 2` (which isn't defined by the module) in your i3 module section and then reference that value with `${self.padding}` in all the `label-*-padding` keys, so that you don't have to hardcode that value in multiple places. And we want people to have that ability, without polybar spewing errors
