### ISSUE TITLE
Polybar geometry not respected

### ISSUE THREAD

**Issue by Longhinus** [jaagr/polybar#1188]
I recently ran over a problem in i3wm
![a](https://user-images.githubusercontent.com/34583123/39100314-193d07f8-4688-11e8-9711-b1ca600b7130.png)
As you can see the geometry of the bar is not rendered properly.

I built polybar with all the dependencies installed and without errors.
I am currently running i3wm from Airblader (development version from 4-22-2018) and the latest version of polybar (3.1.0-110-gff39c9d-git). By the way my distro is debian sid.

**Comment by patrick96** [comment]
You mean `offset-x` with a `width` that is not 100% is not respected? i3 will forcibly position polybar, you can turn that off by setting `override-redirect = true`, however this means that i3 will stop reserving space for polybar. I think currently the only way to get the best of both worlds, is to start a fully transparent bar that has the same height and `override-redirect = false` so that i3 makes space for the bar while not repositioning the bar you actually see.

**Comment by Longhinus** [comment]
I finally found a solution, it is to set he following values in my bar ([bar/example]) configuration:
`border-left-size = 48`
`border-top-size = 20`
It's a bit of cheating, but better than rendering another bar beneath the actual one, beside my composite manager makes it pretty blur.

**Comment by patrick96** [comment]
Yeah that works too. If you have window shadows, they may look weird though
