### ISSUE TITLE
How to set a keybind to show polybar?

### ISSUE THREAD

**Issue by The-Soulless** [jaagr/polybar#1209]
i3bar has a feature where it autohides the bar and if you press $mod it shows it, even above fullscreen windows. This was nice as it gave me more screenspace and let me check the time whilst watching videos with mpv. Does polybar have a feature similar to this, at least having the $mod key show the bar above fullscreen windows?

**Comment by patrick96** [comment]
polybar has [IPC](https://github.com/jaagr/polybar/wiki/Inter-process-messaging#command-messages-to-control-polybar) functionality, you can add a keybind to call `polybar-msg ... ` to hide/show the bar. If you have `override-redirect = true`, it should display above fullscreen windows. But you can't toggle the same bar being displayed above and below fullscreen windows.
What you want is achievable, but you'll probably need to use two bar instances, one with `override-redirect = true` and one with it set to `false`

**Comment by The-Soulless** [comment]
Eh, I guess I'll just set a keybind to toggle polybar and turn override-redirect on, would be really nice to have the feature fully though.

**Comment by patrick96** [comment]
There isn't really a WM independent way to toggle the bar being below and above fullscreen windows because of how WMs handle restacking. For example in i3, if I raise the bar to the top, it will stay there and I have to manually restack it. But in herbstluftwm, the bar will stay at the top, until I (re-)focus the fullscreen window, at which point the fullscreen window is at the top again. The main issue here is to restack polybar, we have functions that do that for us in i3 and bspwm but not other window managers, because the procedure is a little different depending on the WM. If we find a way, this wouldn't be difficult to implement. But for now I think, we'll leave this be.

**Comment by QiangF** [comment]
There is a promising work around using polybar-msg using a key remapper and key down key up events.
I need help from someone who is more familiar with polybar.
https://github.com/k0kubun/xremap/issues/72

**Comment by QiangF** [comment]
I got it working with these commands

    xdo raise -N Polybar
    xdo lower -N Polybar

But the system tray icons are disconnected with other bar component. When other par is shown, the tray icons are missing; when tray icon is shown, other part is hidden.
