### ISSUE TITLE
IPC Hooks / Simple click events without exec change

### ISSUE THREAD

**Issue by andrewtheone** [jaagr/polybar#1232]
Hey!
I'm looking at polybar, its cool but my question is can I have a module which tails, and have polybar dispatch click/scroll events and NOT change the tail command?

What I'm trying to do:
Have a script which tails, and runs forever, and I'd like polybar to dispatch click events to it like ipc hooks and not change the command which currently tails, in other words I only want a signal from polybar on stdinput that the user has clicked/scrolled on my module. I have a heavy module which monitors multiple servers (mem, hdd, services, etc), and I'd like it if i could click on the module and the module would get that I clicked, and could perform something. (without changing the currently running process, just sending a signal to it). 

Currently alternatively I have a monitor-service and a module.sh, monitor-service runs in the background and module.sh gets the current event from polybar, and sends stdinput to monitor-service and then outputs monitor-service's stdoutput but I think is overcomplicated to have a intermediate script just to put stuff on stdinput and read stuff from stdoutput.

**Comment by patrick96** [comment]
Yes you can!

We recently added a `%pid%` token with the PID of the tailed script to the script click and scroll handlers, so you can for example set `click-left = kill -USR1 %pid%` and trap the `SIGUSR1` signal in your script where you then perform some action.
This is probably the easiest way, if you want to have different behaviour for left and right-click as well as for the scroll direction, you'd have to do something more involved, but because you now can use the PID, you can do basically anything.

The `%pid%` token is not in any release yet, so you need to use polybar compiled against the latest commit for this.

**Comment by andrewtheone** [comment]
how can i trap the sigusr1? lets say in a nodejs app?

**Comment by patrick96** [comment]
That I don't know, the [Wiki](https://github.com/jaagr/polybar/wiki/Module:-script#examples) has an example for bash. `SIGUSR1` is a standard signal so there should definitely be a way to do it in node.
