### ISSUE TITLE
Move to gitlab?

### ISSUE THREAD

**Issue by schaden-freude** [jaagr/polybar#1270]
Microsoft is acquiring Github.

https://blog.github.com/2018-06-04-github-microsoft/

https://blogs.microsoft.com/blog/2018/06/04/microsoft-github-empowering-developers/

**Comment by patrick96** [comment]
I'm aware. I don't think the acquisition will impact this repository in the long term.
I understand the sentiment though, I wouldn't trust MS with my private corporate repo, but I don't think any of us have the capacity right now to perform the move purely for ideological resons.

If things get bad, we can always move to gitlab in the future.

@jaagr, @NBonaparte what are your positions on this.

**Comment by NBonaparte** [comment]
I tried importing it on GitLab a few hours ago and it's still in progress. I guess we can set either this or GitLab as a mirror and do everything on the other one.

**Comment by NBonaparte** [comment]
It finally finished, you can find it at https://gitlab.com/polybar/polybar. Apparently the issues didn't import at all, and obviously open PRs are broken because we don't own the branches.

**Comment by kronn** [comment]
Maybe just having a mirror to cope with network issues or as general backup is a good outcome of this. Can gitlab be configured to be a mirror that is updated automatically?

**Comment by NBonaparte** [comment]
I've set it as a mirror.

**Comment by Dmole** [comment]
All paying projects should move to gitlab so the money goes into the further development of open source. (but that's nothing new)

All projects that are freeloading should move to github to let Micro$oft foot the bill (in order to avoid burdening gitlab).

why gitlab?

- it's the most popular alternative [vs](https://thishosting.rocks/best-github-alternatives/)
- it has ab open source version used by Debian.
- it uses google cloud (and google makes open source like android and chromium) [ref](http://www.datacenterknowledge.com/cloud/how-did-gitlab-scale-slashdot-effect-point-and-click)

**Comment by patrick96** [comment]
Going to close this. A permanent move is not going to happen unless really necessary.
