### ISSUE TITLE
No workspace shown (i3)

### ISSUE THREAD

**Issue by Kompwu** [jaagr/polybar#1271]
Hi, i can't figure it out...
No errors at launch of Polybar, everything's fine except this.
[Config](https://pastebin.com/bv5SzaWU)

**Comment by patrick96** [comment]
Are you sure you don't get any errors in the terminal?
Because I get 
```
error: Disabling module "i3" (reason: The reference ${module/bspwm.label-focused-padding} does not exist (no fallback set))
```

You are using multiple references to the bspwm module in the i3 module (`${module/bspwm.label-focused-underline}`) and because you don't have the bspwm module defined, polybar can't resolve the reference and disabled the whole i3 module.

Use actual colors and padding values instead of `${module/bspwm....}` references.
