### ISSUE TITLE
Add module to read from stdin

### ISSUE THREAD

**Issue by nkoep** [jaagr/polybar#1378]
As an xmonad user, I'm glad there's a pretty straightforward way to get xmonad's event log to display workspaces, tiling mode, window title, etc. in polybar. The current solution outlined [in the wiki](https://github.com/jaagr/polybar/wiki/User-contributed-modules) involves using a script module which tails the contents of a named pipe which xmonad writes to. With xmobar, this seems slightly easier since xmobar also allows reading input from stdin. I was wondering whether there might be a chance that such a module could be added to polybar to simplify integration with xmonad, and potentially other window managers. If not, no biggie. In any case, thanks for your hard work. Really enjoying polybar.

**Comment by patrick96** [comment]
So your proposed solution would be to change the script to write to stdout instead of writing to a file but everything else would stay the same (except for the polybar module itself)? If you change the script like that you could just as well adapt the script module to directly call and tail that script, or am I missing something?

**Comment by nkoep** [comment]
The idea is to spawn polybar from xmonad, and use an unnamed pipe to send updates to polybar. Right now, xmonad and polybar have to agree on a rendezvous point in the form of a named pipe to exchange information. My suggestion would be to allow polybar to read from stdin directly so you could do something like this instead:
```haskell
prettyPrinter handle = defaultPP { ppOutput = hPutStrLn handle }

main :: IO
main = do
    handle <- spawnPipe "polybar bar"
    let config = defaultConfig
        { logHook = dynamicLogWithPP $ prettyPrinter handle }
    xmonad config
```

**Comment by patrick96** [comment]
Couldn't you change this to instead write into a pipe instead of polybar like this?
```haskell
main = do
    safeSpawn "mkfifo" ["/tmp/.xmonad-polybar"]
    handle <- spawnPipe "tee /tmp/.xmonad-polybar"
    let config = defaultConfig
        { logHook = dynamicLogWithPP $ prettyPrinter handle }
    xmonad config
```

And then use the same module as in the wiki?
The amount of code you would need on the xmonad side would be about the same, the only difference being that you need such a rendez-vous in form of a pipe.

I think the use-case for reading from stdin is quite narrow because polybar would have to be spawned by the process that will write to stdin. We're probably not going to implement this, but I have added an entry to our Feature Request project for a module that displays content you send to it via ipc

**Comment by sagotsky** [comment]
@nkoep I wrote a wrapper you might find interesting.  It dumps stdin into a pipe and launches polybar.  This lets me launch xmonad the way I'm used to and polybar can follow the pipe.

https://github.com/sagotsky/.dotfiles/commit/2a1a911ca898e41a5adb2b2199e1540ae0c3defd
