### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by TonCherAmi** [jaagr/polybar#1410]
@jaagr @NBonaparte @patrick96 @skystrife, hi everyone.

You all most likely already know what [Github Pages](https://help.github.com/articles/what-is-github-pages/) is, if not, the link explains it well enough.

I think it would be really awesome if polybar had an actual home page and since hosting is not something we would need to worry about thanks to gh-pages, the only thing needed  to realize that would be the site itself.

Which we also now have. Well, I made something resembling one, at least.
You can take a look at it right now at [toncherami.github.io/polybar](https://toncherami.github.io/polybar). It's not much more than a glorified version of the current README, but I like to think that it looks fairly decent, hopefully you do like it.

Technologies used: it is basically plain HTML/CSS + Bootstrap (CSS only) with only like four lines of JS (the scroll-down button callback). I also used Google Fonts and Font Awesome. The source currently resides [here](https://github.com/TonCherAmi/polybar/tree/gh-pages).

Now, if you do decide that it's good enough to be the official home page of polybar, there are two ways we can go about setting it up:

1. The first and the more preferable one, in my opinion, would be to create a repository called `polybar.github.io` under the [polybar organization](https://github.com/polybar/) and have it merged there, which would result in it having the `polybar.github.io` domain.
2. The other way is to simply open a PR here and merge it into the `gh-pages` branch. That would result in it having the domain of `jaagr.github.io/polybar` which, I believe, is hardly as neat as the first option.

It's ultimately up to you though. For details see [here](https://help.github.com/articles/user-organization-and-project-pages/).

I welcome suggestions (as long as they're not too drastic) and criticism, especially regarding the wording as I'm not too confident in it. I'd also appreciate it if you could point out any issues you find.

Can't wait to hear your thoughts!

**Comment by patrick96** [comment]
Wow, the page design looks amazing, thank you very much!

I was planing to create a homepage for polybar as well to maybe also host blog posts about most recent changes, announcements and so on. But I wanted to wait until we agreed that we are going to migrate all polybar repositories to the organization. I actually scheduled to do a migration testrun with dummy repositories in a few weeks.

I particularly like the feature spotlight in the grid.
I think we can use most of the webpage as is with a few minor modifications:
* Incorporating the polybar logo into the site
* For the rices at the bottom, we probably have to ask the creators for permission and we should also link to the [/r/unixporn](http://reddit.com/r/unixporn/) post as well as use the clean screenshot (without open windows) if available.
* While the three bars at the top look great, it would be better, if they were actually generated with polybar, to not give the wrong impression to people, but I think, we should be able to do most of the things on there with polybar.


Guys what do you think? If you're down with adding a webpage, I will create the `polybar.github.io` repo in @polybar.

**Comment by rmw5601** [comment]
In regards to my screenshots being used on this homepage, @patrick96 said that he thought clean screenshots with no windows open would be more suitable for this. I agree and I am willing to provide screenshots of the 3 polybar configs used on the webpage with no other windows open if they would be used on the homepage instead of the ones which were included in my reddit posts.

**Comment by jaagr** [comment]
I think it looks awesome! Great job @TonCherAmi! A website is a living thing so I will not comment on specifics right now since it can be changed later. I vote for making it public as the official Polybar website.

**Comment by NBonaparte** [comment]
Great idea, this would be an excellent addition to the repo.

Since a blog has been suggested, it might be useful to create a Jekyll theme that matches the current design, so we can easily just create posts in markdown and simply our workflow.

Some quibbles on the design (just my thoughts based on my tastes, don't feel offended or obliged to change):
* Megrim (used for the logo in the top left) is horrendous and Josefin Sans isn't well suited to body text. 
* Too white/plain, feels like I'm going blind. We should have at least one other color.

This is probably a dumb and useless idea, but since you have a "simulation" of the bar, what if we had some form of GUI to show/hide different modules and generate a config?

**Comment by TonCherAmi** [comment]
@NBonaparte having a markdown powered blog sounds pretty neat, though I do have no experience with Jekyll whatsoever. I might look into it if I have free time.

Regarding them quibbles:
- I am not one hundred percent sold on that myself, so I would be down to change it for something it different. What do you think of [Flamenco](https://fonts.google.com/specimen/Flamenco) for example?
- Huh, I believe Josefin Sans is only used for headings and subheadings, if that's what you mean then I guess it's just that our tastes differ. I am totally open to suggestions though, so feel free to suggest something you think would fit better, I'd be glad to check it out.
- Well, minimalism is what I was going for, so I guess that's that. I could probably try making the background a little grayer to not cause as much 'eye burn', though I personally have never had any issues with that. (am I the only one who keeps the lights on at night or what?)

That actually sounds like a really awesome idea, though I feel that implementing it without any frameworks would require some sort of a JS ninja, which I am certainly not, heh.

**Comment by NBonaparte** [comment]
* Flamenco is a little bit better, still not too sold on it though.

* Sorry, I meant Comfortaa, although I guess my criticism applies to the smaller subheadings (< 20pt) as well. Both fonts are meant to be used at larger sizes, according to the designers. From the popular pairings suggested by [Google Fonts](https://fonts.google.com/specimen/Josefin+Sans), I think Montserrat looks the best (Lato looks nice as well).

* Grey tones might help, a single accent color might be nice as well.

Also just noticed that the center mockup bar's shadow is different from the others, is this intentional?

**Comment by patrick96** [comment]
I'm on vacation for the next week, I'll have a look at it afterwards.

**Comment by x70b1** [comment]
Cool! :+1:

**Comment by patrick96** [comment]
I think the black-white logo in the navbar looks really good. Would it also work as a favicon?

About the images, @rmw5601 if you can still recreate the exact same bars for all three rices this would be perfect, otherwise don't worry about it and we'll use the busy rices.

@TonCherAmi I have just a few minor changes, after that please open a PR in https://github.com/polybar/polybar.github.io, we will discuss having you as a maintainer for the webpage once we move everything to the organization but I don't think there is anything speaking against it.

* In the feature spotlight the description should also link to the wiki not just the icon. 
* Replace ` ALSA and PulseAudio Volume Controls` with just `Volume Controls` that directly links to the pulse module
* Since the tray has some issues right now, I don't want to directly promote it, please change the tray feature to something like cpu, ram, or battery

**Comment by patrick96** [comment]
Yeah, I suspected there was too much detail in the other one, the current one will do.

I have recreated the repo to now be empty. You should be good to go.

**Comment by TonCherAmi** [comment]
I have not foreseen this :confused: 
![image](https://user-images.githubusercontent.com/13941584/45688382-e4ce2a00-bb59-11e8-9646-34bd6d31c0c2.png)

**Comment by rmw5601** [comment]
Here are the clean versions of the screenshots.

[screenshot 1](https://u.teknik.io/SLQWC.png)
[screenshot 2](https://u.teknik.io/GMwIL.png)
[screenshot 3](https://u.teknik.io/iYVql.png)

**Comment by patrick96** [comment]
The site is now live at https://polybar.github.io/

**Comment by NBonaparte** [comment]
@patrick96 could you invite all of us to join the organization?
