### ISSUE TITLE
Weird width on date module

### ISSUE THREAD

**Issue by hallonfras** [jaagr/polybar#1433]
## Describe the issue
*A clear and concise description of what the bug is.*

My bar starts looking weird because my date module changes width as the days of the week do

**Expected behavior:**

I would expect the module to stay the same width but the text within to get cutoff if it is too big.

*A clear and concise description of what you expected to happen.*

```

## Screenshots
*If applicable, add screenshots to help explain your problem.*
![2018-09-21-140520_5520x2160_scrot](https://user-images.githubusercontent.com/42581623/45880341-decd8880-bda7-11e8-9dea-118991182153.png)

## Environment:
* WM:Openbox

**Comment by hallonfras** [comment]
![2018-09-21-140520_5520x2160_scrot](https://user-images.githubusercontent.com/42581623/45880380-058bbf00-bda8-11e8-8781-54af357801d6.png)
Here is a clickable link of a screenshot

**Comment by patrick96** [comment]
There are various ways to enforce a fixed width module:
* You can set min and max width to the same number in the [tokens](https://github.com/jaagr/polybar/wiki/Formatting#tokens), this allows for time and date to each have a fixed width.
* Set `label-maxlen`, which enforces a max length on the label. The label can still be smaller, to fix this, you can pad the label to the right with spaces so that it always is atleast `label-maxlen` characters wide (Note: You need to surround the label value with quotes if you do this). There is no way to have it anything else than left-aligned, so this is not a perfect solution.
