### ISSUE TITLE
Polybar complains about jsoncpp when launched from i3

### ISSUE THREAD

**Issue by Probotect0r** [jaagr/polybar#1455]
## Describe the issue
I have this line in my i3 config:
```
exec_always --no-startup-id ~/.config/polybar/launch.sh
```
and these lines in the launch.sh script:
```
killall -q polybar
polybar default > ~/polylog 2>&1
```
When I launch i3 or refresh it, the contents of `~/polylog` are:
```
polybar: error while loading shared libraries: libjsoncpp.so.11: cannot open shared object file: No such file or directory
```
However, when I run the launch.sh script from a terminal, polybar loads fine. I  am running Arch Linux and have the jsoncpp package installed (v1.8.4-2). I installed polybar using the `polybar` package in the AUR (clean installed after installing jsoncpp).

 I understand that this is likely not a polybar issue but I am not sure where else to ask.

**Expected behavior:**
Polybar should launch when launched from i3.

**Actual behavior:**
Polybar throws an error about missing jsoncpp when launched from i3, but runs perfectly fine when run from a terminal.

## To Reproduce
My config has nothing special, just the i3 module and the systray.
```
[bar/default]
monitor = DVI-I-1
width = 100%
height = 26
padding-left = 2
padding-right = 2
module-margin-left = 2
module-margin-right = 2
modules-left = i3 xwindow
tray-position = right
```
## Polybar Log
Output when run from i3 (not terminal):
```
polybar: error while loading shared libraries: libjsoncpp.so.11: cannot open shared object file: No such file or directory
```

## Environment:
* WM: i3-gaps
* Output of `polybar -vvv`:
```
polybar 3.2.1

Features: +alsa +curl +i3 -mpd +network +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
For some reason you have a stray `libjsoncpp.so.11` file in your system somewhere that polybar links against when building but doesn't always find. The version of jsoncpp you are using actually provides `libjsoncpp.so.20`

Please try finding the `libjsoncpp.so.11` file with either `locate libjsoncpp.so.11` or `find / -name "libjsoncpp.so.11"` and seeing which package it belongs to with `pacman -Qo /path/to/libjsoncpp.so.11`
Please post everything you find here. This is likely a misconfiguration on your system but I don't want to rule out an error on our side yet. Because polybar actually builds jsoncpp alongside polybar if you don't have jsoncpp 1.7.7 or newer and the version that it builds actually would create `libjsoncpp.so.11` but it should be disabled, so it's definitely possible that we have messed up.

**Comment by Probotect0r** [comment]
`find / -name "libjsoncpp.so.11"` doesn't return any results.

**Comment by Probotect0r** [comment]
I ended up following the symlink advice from #963 and it is now working for me as well. Is there anyway I can help find the root cause for this?

**Comment by Probotect0r** [comment]
I have a polybar binary in `/usr/local/bin/polybar` and one in `/bin/polybar`. I guess I must have compiled one version a while ago and it landed /usr/local/bin and that's what i3 is picking up. 

Thanks for the help.
