### ISSUE TITLE
Colons in click-* handlers sometimes considered special

### ISSUE THREAD

**Issue by dkasak** [jaagr/polybar#1463]
## Issue

Having two colons in a `click-*` handler (e.g. `click-left`) makes polybar consider the colon a special character, preventing the module from executing.

For instance, this works as expected, spawning a notification when the module is clicked:

    click-left = notify-send whatever :

This also works:

    click-left = notify-send whatever a && notify-send whatever :

However, the following fails:

    click-left = notify-send whatever : && notify-send whatever :

The error message given is:

    error: Failed to parse contents (reason: Unrecognized token ':')

Escaping the second or both colons makes it work again, but escaping just the first one *doesn't*.

So these both work:

1. `click-left = notify-send whatever : && notify-send whatever \:`
2. `click-left = notify-send whatever \: && notify-send whatever \:`

But this does not:

    click-left = notify-send whatever \: && notify-send whatever :

I expect the colon to not be special at all here, since it's not within a `%A{...}` or similar escape code.

## To reproduce

    [bar/example]
    modules-left = test-colon

    [module/test-colon]
    type = custom/script
    exec = echo foo
    interval = 5
    click-left = notify-send whatever a && notify-send whatever :

## Environment:

* WM: xmonad
* Output of `polybar -vvv`:

```
polybar 3.2.0-54-g9968080-git

Features: +alsa +curl -i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/clang++
Compiler flags:  -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors -Wno-error=parentheses-equality -Wno-zero-length-array
Linker flags:
```

**Comment by patrick96** [comment]
Thanks for reporting. I already proposed a fix for this in #1457 a few days ago.

The same bug was also reported in #984.

What polybar does with `click-*` commands is it wraps them into an `%{A...}` action block. Because polybar first generates a string similar to a lemonbar input string from all it's modules and then hands that to the parser. However it fails to properly escape all the colons in the command, it always only escapes the first one (even if it is escaped already).

So
```dosini
click-left = notify-send whatever : && notify-send whatever :
```
would generate
```
%{A1:notify-send whatever \: && notify-send whatever ::}
```

But actually 
```
%{A1:notify-send whatever \: && notify-send whatever \::}
```
should be generated.
