### ISSUE TITLE
Possibility to set additional environment variables in a script module

### ISSUE THREAD

**Issue by dkasak** [jaagr/polybar#1465]
## Is your feature request related to a problem? Please describe.
Sometimes I need to configure some things in a `custom/script` module but I would prefer not to edit it. For instance, this may be because it's from the polybar-scripts repo and I don't want to change its source code so that I can more easily update it in the future without manual and error-prone merges. I would also prefer not to set an environment variable globally since this pollutes my environment and increases the possibility of clashes and weird bugs. Additionally, setting environment variables globally means that I probably have to re-login before it takes effect.

## Describe the solution you'd like
It would be nice if modules allowed setting additional environment variables to be passed to the script (in the `custom/script` scenario) and its event handlers (in all modules supporting these), e.g.

```
env-0 = FOO=bar
env-1 = BAZ=quux
exec = myscript.sh
click-left = myclickhandler.sh
```

So that both `myscript.sh` and `myclickhandler.sh` now had variables `FOO` and `BAZ` available, in addition to the inherited environment.

It might also be useful to support something like `inherit-environment = no` so that the inherited environment is cleared before executing the scripts.

## Why does polybar need this feature?
Configuring scripts is a common need and I've described above why I think some common mechanisms are inadequate for this use case. With this feature, scripts specifically written for polybar (and other scripts exposing configuration variables) could be configured during module definition without editing their source code, enhancing modularity.

## Describe alternatives you've considered
I've considered setting the variables globally, which has the downsides described above. I've also considered setting the variables inline:

`exec = FOO=bar BAZ=quux myhandler.sh`

While this is appropriate for short options, it can get unwieldy when several and/or longer options need to be passed. This is compounded by the fact that the config parser doesn't support line continuations so that this can be formatted tidily. Additionally, it doesn't solve the problem of the variables not being available in event handlers (without repeating them on those lines as well, of course).

**Comment by patrick96** [comment]
I don't really see the usefulness of such a feature.
Are there many polybar scripts out there that use env variables for configuration instead of command line arguments? If you need to do so much configuration for a polybar script, when calling it, that a single line isn't enough, you're better off using a wrapper script anyway or have a script that exports the variables for you, so you could do `exec = source myenv.sh && myscript.sh`.

You could also export those variables in the script where you run `polybar`, so polybar, and in turn all the commands it executes, inherit them.

I understand that this would make it a bit more convenient for your use case but the other methods I described are by no means unwieldy and all require only a constant amount of extra code in addition to exporting the env variables once. My recommendation would be the wrapper script and if you really need to have the same env variables in the click commands as well, the `source myenv.sh` approach.

> It might also be useful to support something like `inherit-environment = no` so that the inherited environment is cleared before executing the scripts.

This would not be possible because it would also purge env variables like `$HOME` or `$SHELL`.
