### ISSUE TITLE
Polybar multiple error (on successful build)

### ISSUE THREAD

**Issue by Asynchronousx** [jaagr/polybar#1494]
Hey there.
I'm running on Debian 9.5.0.
I'm trying to run the polybar example (the first default config) but i'm having a lot of errors even if the build was successful and everything installed is good.

This are the errors:

warn: No monitor specified, using "eDP-1"
error: Disabling module "bspwm" (reason: Could not find socket: /tmp/bspwm_0_0-socket)
error: Disabling module "i3" (reason: Could not find socket: <empty>)
error: module/mpd: Connection refused
error: module/xbacklight: Could not get data (err: XCB_NAME (15))
error: Disabling module "xbacklight" (reason: Not supported for "eDP-1")
warn: pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo
error: module/mpd: Connection refused
error: tray: Failed to put tray above 0x3400002 in the stack (XCB_MATCH (8))
warn: Systray selection already managed (window=0x2000019)
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e238)
warn: Dropping unmatched character  (U+e0ca)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e21a)
warn: Dropping unmatched character  (U+e238)
warn: Dropping unmatched character  (U+e0ca)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
error: module/mpd: Connection refused
.
.

and they continue until i press CTRL+C.

There is any fix to this annoying problem?

thank you.

**Comment by patrick96** [comment]
For the unmatched characters, check out the [Font Wiki Page](https://github.com/jaagr/polybar/wiki/Fonts#debugging-font-issues).

The other errors all mean that either, the module doesn't work on your machine or that it isn't configured properly. Have a look at the [wiki](https://github.com/jaagr/polybar/wiki) page for each module to see how to configure them.
For example, the i3 module throws an error because you are probably not running i3.

The example config should just showcase what is possible with polybar. It is not supposed to be used as is, you will have to go in an configure each module for your needs and remove the ones you can't use.
