### ISSUE TITLE
Size of polybar binary on Ubuntu Cosmic

### ISSUE THREAD

**Issue by vaskark** [jaagr/polybar#1497]
Hi. I recently upgraded to Ubuntu Cosmic and was using polybar 3.2.1 which was about 70 Mb as a binary. I've since rebuilt polybar but now the binary is 142 Mb (with polybar-msg being 1.1 Mb). Is this normal? I also have an Arch virtual machine and the polybar binary is only ~2 Mb there.
Just wondering if anyone can shed any light on this. It works fine, btw. Just seems odd.

**Comment by patrick96** [comment]
Hmm, by default polybar uses the cmake build type `RelWithDebInfo`. Which still includes debug information inside the executable. We should probably make `Release` the default or at least adapt all guides and build scripts to use the 'Release' build type.

On arch you have such a small size because it strips debug information by default when instaling.

**Comment by vaskark** [comment]
Thanks for responding and for clearing up my confusion.
