### ISSUE TITLE
Bar Button to toggle pm-powersave issue/question

### ISSUE THREAD

**Issue by flahertyian** [jaagr/polybar#1508]
The basic goal of what I am trying to accomplish is to have a button on the bar that toggles pm-powersave the issue I am running into is two fold. First I don't want to have my script run on an interval, I just want it to execute when the button is pressed. Second currently when I link my module the bar seems to remove other modules, specifically the modules aligned to the right, they just become invisible (pulseaudio, batery, and date modules).
if you need any more information about my config please ask :+1: 
additional question:
is there a way to save the state of the script on i3 reload without re-runing the script

;[module/powsave]
;type = custom/script
;label = powSaver:%output%
;format = %{A1:~/.config/polybar/powMode.sh} <label> %{A}
;exec = ~/.config/polybar/powMode.sh
;interval = 1000000

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bs@bs-ubuntu:~/.config/polybar$ cat powMode.sh 
#!/bin/bash

#polybar script for switching powersaving mode

if [ -z "$pmMode" ]; then
  export pmMode="false"
  #sudo pm-powersave false 
fi

if [ $pmMode == "false" ]; then
  #sudo pm-powersave true
  pmMode="true"
  echo "ON"
else
  #sudo pm-powersave false
  pmMode="false"
  echo "OFF"
fi

**Comment by patrick96** [comment]
There currently is no built-in way to run the `exec` script only when you click the modules. If you want to achieve this, you will have to program the update functionality into the script. The easiest approach would probably be to use a non-terminating script with `tail = true` and in that script you listen for some signal (preferably `SIGUSR1`) which would make the script update its output, similar to the date example in the [wiki](https://github.com/jaagr/polybar/wiki/Module:-script#examples).

As for the other issue, the cause is likely that your action tag is malformed: `%{A1:~/.config/polybar/powMode.sh} %{A}` there is supposed to be a colon after the command.
