### ISSUE TITLE
 Unintuitive font config behavior

### ISSUE THREAD

**Issue by stellarhoof** [jaagr/polybar#1519]
## Describe the issue

`font = ` behaves differently from `; font =`

**Expected behavior:**

In both cases I'd expect it to get the font given by `fc-match`

**Actual behavior:**

`; font =` defaults to a "`fixed`" bitmap font.

**Comment by patrick96** [comment]
Why is this the expected behavior?
Polybar uses `fixed` as the fallback font when you don't specify any fonts.

If you set
```dosini
font-0 =
```
you are explicitly setting the font pattern to the empty string which is then passed to `fc-match`.

However with
```dosini
; font-0 =
```
the line is a comment and polybar will not even read what's on it, thus you didn't actually specify any fonts in your config and polybar will use the fallback `fixed` and pass that to `fc-match`.

You should always specify a font, the fallback font is only here in order for your bar to still at least show up, even if you forgot to add fonts to your config.

**Comment by stellarhoof** [comment]
> polybar will use the fallback fixed
That is what is unintuitive. The fallback should be whatever is returned by `fc-match` with an empty string. I don't kow if `fc-match fixed` always works, but `fc-match` should do so.

**Comment by patrick96** [comment]
I still don't see a reason to change this behavior. Polybar will warn you if you didn't specify any fonts. What you are proposing of course also works but for me neither of them is more intuitive than the other.

> I don't kow if `fc-match fixed` always works

`fc-match` always returns a value, even if the font doesn't exist. What I have noticed is that it always returns whatever `fc-match ""` returns, if the font is not found.

> Assuming you mean bitmap fonts with fc-match fixed, the user might have disabled bitmap fonts.

`fc-match` will not give you a bitmap font if they are disabled

**Comment by stellarhoof** [comment]
> neither of them is more intuitive than the other.

Fair enough. The reason it's unintuitive to me is that I don't see a reason for `font-0 =`. Its semantic meaning is (for me at least), exactly the same as if `font-0` was never defined in the first place. As a matter of fact, `font-0 =` should be a syntactic error in my eyes. As it stands, even with the new parser (https://github.com/jaagr/polybar/pull/1237) there's too many different ways of specifying the absence of a value:

- Not defining the configuration attribute
- `attr =`
- `attr = ""`

Ideally, there should only be one way of conveying the intention of the absence of a value (which is different from the presence of a value but empty). E.g. `foo = None` != `foo = ""`

**Comment by patrick96** [comment]
I see your larger point about absence of values. In the current implementation `key = ` is the only way to specify that a value is supposed to be the empty string, `key = ""` unfortunately is interpreted as the literal string `""` (which I consider a bug and is fixed in #1377).

Not defining `foo` is already different than `foo = ""`. For example setting `format-disconnected =` in the network module will make the module produce no output if the network is disconnected. Not defining the key at all will make polybar produce an error that you didn't define the key.

Currently the semantics are as follows:
* The only way to signal the absence of a value is to not define its key.
* Setting `attr` to the empty string can be done with either `attr =` and `attr =""` (once #1377 is merged).

Unfortunately there is no way to explicitly signal that a value should not be defined. We can't use `foo =` for this because this would break a lot of things since it's currently the only working way of using the empty string. We also can't really use some kind of keyword like `None`, because what if someone wants to intentionally set it to that value. This is kind of unfortunate but I don't see a good way to do this.

> Its semantic meaning is (for me at least), exactly the same as if `font-0` was never defined in the first place

The intuition here was that `foo = abc` and `foo = "abc"` are equivalent, so `foo =` and `foo = ""` should be equivalent too. This also makes things simpler in the code because we don't have to care what's inside the quotes and can just copy it (even if it's the empty string)

**Comment by stellarhoof** [comment]
All valid points. It's indeed unfortunate it evolved like that. Thanks for the detailed response.

The  domain space of config file formats is unfortunate IMO. I've only found https://github.com/dhall-lang/dhall-haskell to be simple, consistent, with well-defined semantics, and expressive enough without being a Turing-complete language. Anything else (yaml, xml, ini, toml, etc...) seems like an ad-hoc format to me. Unfortunately, there's too much of a barrier to entry for dhall. Oh well :(

**Comment by patrick96** [comment]
dhall looks far from simple, but definitely very expressive. My goal is to create a proper spec for the config file format as part of the man pages so that it's at least well defined.

I don't think we're going to change our config format anytime soon since it would require all users to switch to the new format.
