### ISSUE TITLE
Proposal: use abseil-cpp

### ISSUE THREAD

**Issue by infokiller** [jaagr/polybar#1547]
Google open sourced great utility libraries via [abseil-cpp](https://github.com/abseil/abseil-cpp).
It should be easy to use it instead of some the utility functions in polybar- things like string, file, and math.
Abseil is very well tested and stable. It also has a C++11-compatible version of `std::string_view` (from C++17). From my limited testing, it builds pretty quickly.

What do you think?

**Comment by patrick96** [comment]
I think we should be very careful with adding new libraries, because they complicate the build for users and because it's one more thing that can break.

Abseil looks neat and we could maybe use some of its functionality (for example when handling time), but there are several reasons why I don't think it's a good idea to use it right now:

* No support for file system functionality (https://github.com/abseil/abseil-cpp/issues/47)
* I couldn't find any math functionality (except for 128 bit uints)
* The only thing I could find that we can use are string and time methods
* It has to be built from source together with the project (no shared libraries), see [here](https://abseil.io/about/compatibility#what-users-must-and-must-not-do). We cannot rely on pre-packaged shared (or static) libraries.

It seems to me that abseil isn't that useful to us right now. If you can convince me otherwise and show how we can replace a good portion of our utility code with abseil, I'm open to reconsidering.

**Comment by infokiller** [comment]
Sounds very reasonable, thanks for taking the time to review my request!
I will start using abseil in my fork, and if/when I will see significant code that can be replaced, I will reopen this issue.
Thanks!
