### ISSUE TITLE
help with this font issue

### ISSUE THREAD

**Issue by tjw0lf** [jaagr/polybar#1594]
I'm getting this. But the symbol appear in text so unsure why it's not showing up someone please help

warn: Dropping unmatched character  (U+f348)

**Comment by patrick96** [comment]
Did you read the [Font Wiki page](https://github.com/jaagr/polybar/wiki/Fonts)?

**Comment by fbreitwieser** [comment]
Thanks for this awesome program! Just started using it and love polybar.

However, it also took me some time to get rid of all the "Dropping unmatched character" issues. First due to improper font definitions, which I think is well described in the Wiki, but not immediately apparent, and then due to the fonts not having the symbols I wanted. E.g. few fonts have the moon symbols (🌒, etc, only DejaVu Sans) or all the volume icons (🔉, etc, only Noto Symbols 2 on my system).

I made a little Perl script to find the fonts that have a given character, and it might be useful to others.
![image](https://user-images.githubusercontent.com/516060/51771393-da4b1080-20b6-11e9-80d1-a44a6bf4d1fc.png)

```perl
#test-fonts.pl
use strict;
use warnings;
use Font::FreeType;
my ($char) = @ARGV;
foreach my $font_def (`fc-list`) {
    my ($file, $name) = split(/: /, $font_def);
    my $face = Font::FreeType->new->face($file);
    my $glyph = $face->glyph_from_char($char);
    if ($glyph) {
        print $font_def;
    }
}
```

**Comment by patrick96** [comment]
@fbreitwieser Nice script! I have added it to the wiki, maybe it will be useful to other people :)
