### ISSUE TITLE
Update wiki for fedora 29 build ?

### ISSUE THREAD

**Issue by ChTBoner** [jaagr/polybar#1624]
Hello,

While following the wiki to build polybar on Fedora 29, I noted the xbc-util-xrm dependency for Fedora (libxcb-xrm-devel) is not available in the repos anymore.

It seems the solution offered for OpenSuse (xcb-util-xrm-devel) is available though, and it worked for me.
I now have xrdb support after recompiling and resinstalling polybar.

Thanks for the fantastic tool that is polybar.

**Comment by patrick96** [comment]
I actually can't find any reference to `libxcb-xrm-devel` for fedora at all, but I found [this](https://rpmfind.net/linux/RPM/fedora/29/x86_64/x/xcb-util-xrm-devel-1.3-2.fc29.x86_64.html) which is actually for fedora. Maybe it was a mistake when the table was created (by me :wink:), because `libxcb-xrm-devel` is listed on rpmfind, but for Mageia. Thanks for telling us, I have updated the wiki with the proper package name.
