### ISSUE TITLE
filesystem module not working on freeBSD

### ISSUE THREAD

**Issue by binaryplease** [jaagr/polybar#1627]
## Describe the issue

Filesystem module does not work on freeBSD, it shows "not mounted" for the "/" mountoint.
I'm using this configuration:

```dosini
[module/filesystem]
interval = 25
mount-0 = /
type = internal/fs

format-mounted-underline =  ${colors.color-line-1}
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}

label-mounted =  %mountpoint%%{F-}: %percentage_used%% [%free%]
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.foreground-alt}
```

And just see "/ not mounted" in my bar.

**Expected behavior:**
The used/free space should show in the bar.

**Actual behavior:**
"/ not mounted" is shown

**Was it working before?**
It works fine on a different system (linux) with the same config.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[module/filesystem]
interval = 25
mount-0 = /
type = internal/fs

format-mounted-underline =  ${colors.color-line-1}
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}

label-mounted =  %mountpoint%%{F-}: %percentage_used%% [%free%]
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.foreground-alt}

```
## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
...
warn: module/filesystem: Mountpoint / is not mounted
...
```

![image](https://user-images.githubusercontent.com/1719781/51737647-6c3e2380-208d-11e9-9b34-f2223e0c38fc.png)

## Screenshots

![image](https://user-images.githubusercontent.com/1719781/51737060-f1c0d400-208b-11e9-9a0c-1682252df841.png)

## Environment:
* WM: i3
* Output of `polybar -vvv`:
![image](https://user-images.githubusercontent.com/1719781/51737104-11f09300-208c-11e9-8dab-30331c5697b5.png)

## Additional context
Running on freeBSD, installed with pkg

**Comment by patrick96** [comment]
Polybar is developed in and for linux, the FreeBSD only exists because someone managed to run polybar on FreeBSD and most functionality happened to work. It is actually noted in the package's [`pkg_message`](https://svnweb.freebsd.org/ports/head/x11/polybar/pkg-message?revision=469708&view=markup) file which modules work and which don't. For now FreeBSD support is purely coincidental and will not be guaranteed. That may change if we get regular contributors that use FreeBSD and actually implement the functionality there, but for now we will not test everything we do additonally in FreeBSD as it would slow us down immensely
