### ISSUE TITLE
Module border

### ISSUE THREAD

**Issue by zbigniewzolnierowicz** [jaagr/polybar#1638]
## Is your feature request related to a problem? Please describe.

I'm unable to do a floating bar with borders around individual modules without making a bunch of separate 

## Why does polybar need this feature?

To enable better-looking "floating" bars (background set to #00000000).

## Describe the solution you'd like

A per-module `border` setting.

## Additional context

![An image of the bar](https://i.imgur.com/lnm5iZZ.png)

See that bar between transparent space? I don't want that there. There also is no border on the sides of modules, only on the bordering modules.

**Comment by patrick96** [comment]
Hi, thanks for suggesting.

I'm not quite sure about this feature. With the current way the bar is structured it's not possible to implement, we would have to make some pretty substantial changes to how the bar is rendered.

We won't implement this now. But we may come back to it in the future if make big changes to the renderer.

**Comment by patrick-motard** [comment]
Here is an example of how to do this with the current capabilities:
```
[bar/main]
; require monitor to be connected to load bar
monitor-strict = true
inherit = bar/base
monitor = ${env:MONITOR_MAIN}
modules-right = alsa-switch pulseaudio-tail time calendar
modules-left = ;yadm-checker.sh true
modules-center = i3
background = #00000000
bottom = false 
tray-position = none
height = 3%
padding = 1
line-size = 4
line-color = #f00
; radius = 15

; This creates a fake offset (floating bar)
; offset causes i3 windows to overlap with the bar.
; Not specifying border-color makes it transparent.
border-top-size = 20
; border-bottom-size = 20 ; switch top/bottom based on 'bottom=false/true'
border-left-size = 20
border-right-size = 20


[bar/main.top.left]
; require monitor to be connected to load bar
monitor-strict = true
inherit = bar/base
monitor = ${env:MONITOR_MAIN}
modules-right = 
modules-left = yadm-checker.sh true
modules-center = 
border = 2
width = 8.8%
background = #00000000
bottom = false 
tray-position = none
height = 3%
padding = 0
override-redirect = true
offset-x = 30
offset-y = 20
; underline-size = 4
; underline-color = #f00
; radius = 15

; This creates a fake offset (floating bar)
; offset causes i3 windows to overlap with the bar.
; Not specifying border-color makes it transparent.
border-size = 4
; border-top-size = 7
; border-bottom-size = 7 ; switch top/bottom based on 'bottom=false/true'
; border-left-size = 7 
; border-right-size = 7
border-color = ${colors.nord2}
```

Here is a screenshot of what it looks like. Notice how the left green/yellow module has a border, that's because it's it's own module with fixed positioning and width set to line up with the second bar. The second bar has no left modules, is width 100% with a transparent border. I use transparent border instead of override-redirect because override-redirect is bugged in conjunction with i3wm (really it's i3's fault, i3 windows will overlap with polybar). So the second bar (main) is responsible for setting the boundaries with i3 and the screen edges, then the second bar can use override redirect, offset-x/y, etc. 


![2019-03-28_21:09:34_2556x219](https://user-images.githubusercontent.com/6657259/55204687-f3973880-519d-11e9-9a63-e45390440cef.png)

Couple issues/limitations:

- if your module has a variable width, like the i3wm module for example, which becomes wider/narrower depending on how many workstations you have open, this forces you to select a width for the bar that is wider than the module, and to set the background to some fixed color, which isn't the same as "the border follows the width of the module as it adjusts". Doesn't ruin it, but it's a limitation.

- the positioning logic is incredibly brittle. Setting this up for multiple resolutions can be daunting, even when using percentages. Still totally doable, but would be better if it was handled by c++ in polybar.

I can totally see why the devs don't want to implement it right away. It requires some thought for sure. I came across your issue because i was mid way setting up all the widths/borders/etc and thought to myself "let me just double check to see if this is supported out of the box, because damn that would save me some work!".

**Comment by patrick-motard** [comment]
Here's an example of doing it for left, middle, and right:
![2019-03-28_21:51:56_2561x1439](https://user-images.githubusercontent.com/6657259/55206257-d4030e80-51a3-11e9-8e29-4e0900430a4a.png)

Below is the code. Notice that I chose to leave one module on the main bar. This is because one module must be included for the bar to render. I'll switch the module at some point to one that doesn't do anything. For now it's just being drawn over by the main.top.right bar:
```
[bar/main]
; require monitor to be connected to load bar
monitor-strict = true
inherit = bar/base
monitor = ${env:MONITOR_MAIN}
modules-right = time
; alsa-switch pulseaudio-tail time calendar
modules-left = ;yadm-checker.sh true
modules-center = ;i3
background = #00000000
bottom = false 
tray-position = none
height = 3%
padding = 1
line-size = 4
line-color = #f00
; radius = 15

; This creates a fake offset (floating bar)
; offset causes i3 windows to overlap with the bar.
; Not specifying border-color makes it transparent.
border-top-size = 20
; border-bottom-size = 20 ; switch top/bottom based on 'bottom=false/true'
border-left-size = 20
border-right-size = 20

[bar/main.top.middle]
; require monitor to be connected to load bar
monitor-strict = true
inherit = bar/base
monitor = ${env:MONITOR_MAIN}
modules-right = 
modules-left = 
modules-center = i3
border = 2
background = ${colors.secondary-bg}
width = 33%
bottom = false 
tray-position = none
height = 3%
padding = 0
override-redirect = true
offset-x = 33%
offset-y = 20
border-size = 4
border-color = ${colors.nord2}

[bar/main.top.right]
; require monitor to be connected to load bar
monitor-strict = true
inherit = bar/base
monitor = ${env:MONITOR_MAIN}
modules-right = alsa-switch pulseaudio-tail time calendar
modules-left = 
modules-center =
border = 2
background = ${colors.secondary-bg}
width = 350
bottom = false 
tray-position = none
height = 3%
padding = 0
override-redirect = true
offset-x = 85.2%
offset-y = 20
border-size = 4
border-color = ${colors.nord2}



[bar/main.top.left]
; require monitor to be connected to load bar
monitor-strict = true
inherit = bar/base
monitor = ${env:MONITOR_MAIN}
modules-right = 
modules-left = yadm-checker.sh true
modules-center = 
border = 2
width = 8.8%
background = #00000000
bottom = false 
tray-position = none
height = 3%
padding = 0
override-redirect = true
offset-x = 30
offset-y = 20
; underline-size = 4
; underline-color = #f00
; radius = 15

; This creates a fake offset (floating bar)
; offset causes i3 windows to overlap with the bar.
; Not specifying border-color makes it transparent.
border-size = 4
; border-top-size = 7
; border-bottom-size = 7 ; switch top/bottom based on 'bottom=false/true'
; border-left-size = 7 
; border-right-size = 7
border-color = ${colors.nord2}

```

**Comment by patrick-motard** [comment]
It also drives me nutts that my volume modules don't have proper padding. I'm going to fix that.... at some point...

All this stuff is checked into my [dotfiles repo](https://github.com/patrick-motard/dotfiles) if you're interested in seeing more. I update it regularly. Star/follow for updates.
I have polybar setup to load themes dynamically based on selection from a rofi menu. Fun stuff.

**Comment by laperex** [comment]
![image](https://github.com/polybar/polybar/assets/89983190/91e578f6-7970-4fe7-a5ea-603cba4c2260)

This solution utilizes just a single bar with transparency.

```
[global/wm]
font-4 = "border:size=1"; the font name can be anything


[module/m_border]
type = custom/text

format = <label>
format-background = ${colors.border_color}
format-foreground = ${colors.border_color}
format-padding = 0

label = "%{T5} %{T-}"

format-underline = ${colors.border_color}
format-overline = ${colors.border_color}
```

**Comment by laperex** [comment]
also, to note. for some reason it will only work if your bar's dpi is greater than 108
