### ISSUE TITLE
Improve build time

### ISSUE THREAD

**Issue by jaagr** [jaagr/polybar#164]
Right now it takes forever to build the project if ccache isn't warmed up.

Clean up header includes, forward declare, etc.

**Comment by SuperCuber** [comment]
Tip: use makefile to only recompile what is needed...

Like literally polybar is the only package on my system that recompiles when updated...
Fix please.

Also, I dunno how but other packages don't ask me to view build files diff, do something about that too maybe? (Using pacaur)

**Comment by jaagr** [comment]
CMake already handles this. I don't have this issue. Configure your build tool.

**Comment by SuperCuber** [comment]
Hmm... Any pointers on what could be causing the issue? I mean like what to configure exactly?
I don't think this is an issue on "my side" though, because this is the only package that does that...

**Comment by skystrife** [comment]
> Like literally polybar is the only package on my system that recompiles when updated...
Fix please.

All packages that you install from the AUR must be built from source. So if the package is implemented using C/C++ (or any other compiled language), it has to be compiled before it can be installed. There's nothing polybar can do about that. This is just how the AUR works. It doesn't provide binary packages.

> Also, I dunno how but other packages don't ask me to view build files diff, do something about that too maybe? (Using pacaur)

This has nothing to do with polybar. This is a feature of pacaur would need to be configured there. Please read the manpage for pacaur using `man pacaur` and look for the sections about configuration options.

**Comment by patrick96** [comment]
Closing this, there is only so much we can do about the build speeds, polybar uses a lot of expensive templating (because of xpp) and it also has quite a lot of files. Right now, from scratch and g++, with a single thread polybar builds in 6 minutes and with a dual-core system (4 threads) it builds in 2 minutes. If you want even faster speeds, consider disabling some features you don't use. If you are not using an AUR helper (or the equivalent for your distro), the cmake generated makefiles should only recompile files that changed, so only the first compilation and major updates will take longer.

**Comment by SuperCuber** [comment]
@skystrife you are trying to tell me that every other package asks for comparison but yours doesn't because of a failure to configure pacaur? I haven't configured pacaur for any other package but I have to configure it for this one?

**Comment by patrick96** [comment]
He's telling you that polybar can't control how your AUR helper (in your case `pacaur`) handles changes in the `PKGBUILD`, polybar doesn't 'ask' for comparison, pacaur does. In general its a good idea to check the diffs because someone could smuggle malicious code onto your computer if your not careful with the `PKGBUILD`s you install.

**Comment by patrick96** [comment]
I don't know why pacaur doesn't ask for comparisons for packages. I have just run an upgrade and pacaur asked me to compare the build files for every AUR package that was being updated:
![2018-05-12-222808_937x123_scrot](https://user-images.githubusercontent.com/2452038/39961326-c3952dc4-5633-11e8-9ce1-e8ef13b29976.png)

Maybe you don't have any other AUR packages installed. Also just FYI, I have just found out that pacaur is no longer maintained, so best to switch over to another AUR helper.
