### ISSUE TITLE
swap-used should be 0 if swap-total is 0

### ISSUE THREAD

**Issue by fdietze** [jaagr/polybar#1642]
## Is your feature request related to a problem? Please describe.
I have two computers which use the same polybar config. One computer has swap, the other one doesn't. I want to show a ramp how much swap is used. The ramp on the computer without swap shows 100% swap usage, which is not what I want to see, since it cannot use any swap.

## Why does polybar need this feature?
It makes configs which show swap-usage as ramp or percentage usable for computers without swap.

## Describe the solution you'd like
If swap-total is 0, set swap-used percentage to 0.

**Comment by patrick96** [comment]
Why would you want to display a swap ramp on a computer that doesn't have swap?

In your launch script you could export an environment variable where you add the swap ramp, if the computer has swap:
```bash
if free | awk '/^Swap:/ {exit !$2}'; then
    export FORMAT_MEMORY="<label> <ramp-swap-used>
fi
```

And in the config you use that variable or fall back to a default if it's not set:
```dosini
format = ${env:FORMAT_MEMORY:<label>}
```

It could also be done by using polybar's own features:
```dosini
[bar/swap]
; Your regular bar section
format-memory = <label> <ramp-swap-used>

[bar/no-swap]
inherit = bar/swap
format-memory = <label>

[module/memory]
...
format =  ${root.format-memory}
```

Then you start the `swap` bar on the PC with swap and the other on the one without. The ` ${root.format-memory}` reference, gets a value from the bar section, since you use two different bars, this will give you a different value depending on the bar launched.

It doesn't really make sense to argue how many percent 0 out of 0 total are. Someone else might argue that if it shows 0% used that means that there is still swap left (which in this case there isn't).

**Comment by fdietze** [comment]
> Why would you want to display a swap ramp on a computer that doesn't have swap?

As already said, because I want to use the same config on multiple computers. And if I add swap at runtime I don't want to restart anything to reflect the change.

Thank you for the detailed workaround.
