### ISSUE TITLE
System freeze when clicking polybar to change bspwm desktop

### ISSUE THREAD

**Issue by tlent** [jaagr/polybar#1648]
## System freeze when clicking polybar to change bspwm desktop
Sometimes when clicking on a desktop label shown by the bspwm module the system will freeze. 

**Expected behavior:**

Clicking on the desktop label shown by the bspwm module should switch to that desktop.

**Actual behavior:**

Most of the time it works as expected. Sometimes the screen freezes without changing to the new desktop and all input seems to do nothing. 

**Was it working before?**

I have experienced this bug since I switched to using bspwm about a month ago.

## To Reproduce
I assume the following config is enough to cause the issue:
```dosini
[bar/top]
modules-left = bspwm

[module/bspwm]
type = internal/bspwm
enable-click = true
```
I have not tested that the issue occurs with the minimal config above so [here is my complete config just in case](https://gist.github.com/tlent/c5f6f97393878e6b474c91b5078e3bd1).

Steps to reproduce:
1. Switch bspwm desktop by clicking on a polybar desktop label
2. Repeat until the issue occurs

It will not be easy to reproduce on demand but occurs about once a day in my normal use.

## Polybar Log
[End of the log when the issue actually occurred](https://gist.github.com/tlent/cd97992edefaf8d4e2be88251edca6d6)
[Complete log (very long)](https://gist.github.com/tlent/ffb9d6b529452c26d8d0b606078289ee)

The issue took over 24 hours to happen while I was logging so the complete log is very long. Note the null bytes included at the end. The freeze happens immediately after a click so I believe the final click that caused it would have been logged where the null bytes are. When this log was taken I let the system run frozen for about a minute and then restarted by holding the power button.

## Environment:
* WM: bspwm
* Output of `polybar -vvv`:
```
polybar 3.3.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

## Additional context
If music is playing when this issue occurs it continues to play even as the system appears to be frozen, so I believe polybar is causing bspwm or Xorg to freeze but not the entire system.

I use hibernate and it is possible that this issue occurs only after hibernating. I will try to figure out if it happens without hibernating over the next few days.

When the system is frozen I cannot switch to another tty or do anything.

I have never had this issue occur when using sxhkd hotkeys to switch desktops. It only happens when clicking polybar. I believe this is a polybar issue based on that fact and the null bytes seen in the logs included above.

**Comment by patrick96** [comment]
That doesn't sound good. We've had a report of a full system freeze before (#1179), but OP didn't respond and the freeze happened in i3 and as soon as polybar was started. So I'm not sure they're related.

It still puzzles me as to what polybar could do to freeze the *entire* system, even preventing the switch to another tty. In the log you posted, the characters at the end are literally the `^` and the `@` character no null-bytes. Maybe that got mangled when copying. Can you run `xxd` on the log and report the last few lines:

```
xxd /path/to/logfile | tail
```

This will tell us which exact bytes are in the log.

The curious thing is that before every click the log looks like this:

```
polybar|trace: bar: Detected motion: 0 at pos(7, 15)
polybar|trace: Found matching input area
polybar|trace: Found matching input area
polybar|trace: Found matching input area
polybar|trace: bar: Detected motion: 0 at pos(7, 15)
polybar|trace: Found matching input area
polybar|trace: Found matching input area
polybar|trace: Found matching input area
polybar|trace: bar: Received button press: 1 at pos(7, 15)
```

But when the freeze happens the log doesn't even log the motion detected not to mention the actual click. So polybar seems to freeze before it registers that the mouse is on the bar. If that is the case, this is unrelated to bspwm. Can you try to completely disable mouse events on the bspwm module and see if freezes still happen:
```dosini
enable-click = false
enable-scoll = false
```

To be honest, I am not sure how to properly debug this. We would need to figure out what exactly polybar is doing at the time of the freeze, but that is almost impossible. Either the polybar process is frozen which would mean that any tool we would use to monitor polybar would freeze as well. If polybar isn't actually frozen but only the screen, we would somehow need to detect when the screen freezes and at that exact moment interrupt polybar to figure out where it is in its execution, detecting when the screen freezes seems quite difficult to me.

Another theory is that polybar continues to run normally after the freeze and that the last click is actually logged and is the last click in the logs:

```
polybar|trace: bar: Received button press: 1 at pos(7, 15)
polybar|trace: Found matching input area
polybar|info:  module/bspwm: Sending desktop focus command to ipc handler
polybar|info:  module/bspwm: Parsing socket data: MDVI-D-0:O1:o2:o3:f4:f5:f6:f7:f8:f9:f10:LT:TT:G
polybar|info: module/bspwm: Rebuilding cache
```

Because after that the log is full of messages that the bar contents didn't change and that the bar doesn't need to update because of that.
```
polybar|info:  module/cpu: Rebuilding cache
polybar|trace: bar: Ignoring update (unchanged)
polybar|info:  module/memory: Rebuilding cache
polybar|trace: bar: Ignoring update (unchanged)
polybar|info:  module/cpu: Rebuilding cache
polybar|trace: bar: Ignoring update (unchanged)
polybar|info:  module/memory: Rebuilding cache
polybar|trace: bar: Ignoring update (unchanged)
```

It seems strange that this would happen so often with something like the cpu and the memory module present which update every second.

This would mean that the click (or something directly afterwards) freezes the system but processes actually continue to run. How are you playing music on your system? Is the music played by a background service or by a graphical application? Do you have a keybinding to play/pause music, and if so does it still work when the freeze happens? If the music is played by a graphical application it would make sense that the programs actually continue to run but just the screen freezes.


So after looking through the bspwm repo, it seems they are struggling with freezes as well (don't know if they're complete system freezes though). How do you start polybar? Could you also post your bspwm config.

**Comment by tlent** [comment]
Thanks for looking into this. When I copied the log it only included a blank line at the end so I copied those characters into it to show what I was seeing. Sorry, I should have clarified that. Here is the output of that command:
```
➜ xxd polybar.log | tail
00c31f60: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00c31f70: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00c31f80: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00c31f90: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00c31fa0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00c31fb0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00c31fc0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00c31fd0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00c31fe0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00c31ff0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
```

I was using Spotify at the time that it froze and music continued to play. I do have a keybinding and I will try using it next time it freezes.

Here is my usual bspwm config and the script that starts polybar, bspwm, and sxhkd:

[bspwmrc](https://github.com/tlent/dotfiles/blob/e448102f4548b5d5dfd764a7376f4322a32df8ea/.config/bspwm/bspwmrc)
[wm script](https://github.com/tlent/dotfiles/blob/e448102f4548b5d5dfd764a7376f4322a32df8ea/.config/bspwm/wm) This is run with exec in .xinitrc

Right now I am using [this version of my wm script](https://github.com/tlent/dotfiles/blob/ec4bce2ad9bc722a8133f62b0012ee3efc5c0e1e/.config/bspwm/wm) to log polybar output. (The create function is just to make sequentially numbered log files so I don't overwrite the old ones and I am trying strace just to see what it shows on a freeze (if anything))

I probably should have mentioned that I am running polybar with the `--reload` flag.

Last time it froze I tried different SysRq key combinations to see if they would do anything. They didn't, but this did appear in journalctl:

```
Feb 09 15:33:30 tpca kernel: sysrq: SysRq : This sysrq operation is disabled.
Feb 09 15:33:52 tpca kernel: sysrq: SysRq : This sysrq operation is disabled.
Feb 09 15:34:07 tpca kernel: sysrq: SysRq : HELP : loglevel(0-9) reboot(b) crash(c) terminate-all-tasks(e) memory-full-oom-kill(f) kill-all-tasks(i) thaw-filesystems(j) sak(k) show-backtrace-all-active-cpus(l) show-memory-usage(m) nice-all-RT-tasks(n) poweroff(o) show-registers(p) show-all-timers(q) unraw(r) sync(s) show-task-states(t) unmount(u) show-blocked-tasks(w) dump-ftrace-buffer(z)
Feb 09 15:34:17 tpca kernel: sysrq: SysRq : This sysrq operation is disabled.
```

It seems those hotkeys at least worked while it was frozen but the operations were disabled.

Since it takes so long before it freezes it will take me a while to try different things. I will try running without `--reload` and with `enable-click` and `enable-scroll` disabled ASAP.

**Comment by tlent** [comment]
I will close this for now since it seems to be a bspwm issue. Thanks

**Comment by patrick96** [comment]
Yeah, I found those issues in the bspwm as well. I also don't think those are what's causing it since they seem to be caused by `external_rules_command` and you don't use that. I'm not totally sure it's only a bspwm issue, it may also be the interaction between bspwm and polybar.

I'm curious about what strace has to say when the next freeze happens and whether or not you can still control the music, these kinds of errors are really a pain to debug.

About the null-bytes, either they're caused by you forcefully shutting down the system or polybar completely misbehaves and actually outputs them itself. I think the first option is more plausible. This would also support my theory that polybar continues to run and produce log content.

The `--reload` flag shouldn't have anything to do with this.
