### ISSUE TITLE
Wiki for simple scripts

### ISSUE THREAD

**Issue by memeplex** [jaagr/polybar#1652]
Please consider adding a wiki page or section for user contributed scripts and suggestions. I know there is a repo for this but sometimes you have a nice useful script pretty coupled with your own config and don't have the time to factor it out, fork a repo, make a PR, etc. but you do want to jot down a quick explanation of how to get it working in case anyone else could take advantage of.

This could simply be the wiki of the polybar-scripts repo with a visible reference from the README in the project front page.

**Comment by jstamant** [comment]
Have you considered asking the repo-owner of [polybar-scripts](https://github.com/x70b1/polybar-scripts) to add a wiki for posting quickies?

**Comment by memeplex** [comment]
No, I just thought it was part of polybar, thank you for pointing that out.

**Comment by patrick96** [comment]
@x70b1 What do you think?

**Comment by x70b1** [comment]
It's not an easy question. But I think it helps if I point out that we were at that step already: [13 Dec 2017](https://github.com/jaagr/polybar/wiki/User-contributed-modules/9ab1b84d136bed448ae1278943bffc9b86f73826)

The wiki was good for copy and paste. But it was not possible to improve the code quality. I've criticized and changed that. I rewrote the most scripts from that page to improve them. My idea was to take these scripts to a higher level. What you're experiencing now are my requirements: refactoring, a clean README.md, fix all `shellcheck` issues and add portablity to different shells. But that works. `polybar-scripts` is very popular now and there are not much open bugs.

A question that often occurs is: At which point does a script offer value? Where is the line between `works for me` and `would work for others too`? That's why I can't grab every little detail and try to work on the basic things.

A discussion I've experienced before: 
"I wrote a one liner. Works in 95% of all cases."
My answer: Let's work on the other 5%.
"Oh, no, it's too complicated for me."

That's the point. Do you want working code? Or do you want a quick and dirty hack?

I'm trying to do as much as I can for these people. Look at this PR: [polybar-scripts/pull/114](https://github.com/x70b1/polybar-scripts/pull/114#issuecomment-455372994)
He uploaded a script and couldn't improve it. I refactored the script for him. 

Look at this: [howto_add_world_air_quality_index_data_to_polybar](https://www.reddit.com/r/Polybar/comments/9s5du4/howto_add_world_air_quality_index_data_to_polybar/)
Somebody wrote a script in `nodejs`. Two weeks later the script was available as a `sh`.

What I want to say is: If you have an idea for a script or even code for it: Post it. Or open an issue and post the code if a PR is too difficult for you. If the idea is good, we will work on it. Yes, even a few scripts can do some work. 

I can't prevent you from simply copying your code to the existing wiki page. But then you shouldn't be surprised if I saved the code in my repo 2 weeks later. :sunglasses:

Personally I see no need for a wiki page. I try to collect as much as possible under `polybar-scripts`. But it is a community project. And it is wonderful to see how many people contribute to the `polybar-scripts` repo. We would never have reached this level with wiki entries.

**Comment by patrick96** [comment]
I understand that it could be useful to have a place to collect snippets that could be used for specific purposes. I also understand that @x70b1 wants his repo to have clean scripts that work reliably.

We don't have the capacity to maintain such a wiki page ourselves since we would have to also handle all new issues relating to those scripts. I'd also rather not have these kinds of issues in the same issue tracker as legitimate issues with polybar itself.

If you want to maintain a repo that hosts such scripts, you're welcome to do so and we will gladly link the repo in the wiki and I'm sure @x70b1 would also add a link to his README.

**Comment by memeplex** [comment]
I was just saying to keep a zero-maintenance place where people could dump their stuff and get care of themselves, in a true wiki spirit. It will probably be a very dirty place. The point arose because I had this little pomodoro script which is quite nice, but I don't have the time to decouple it from my stuff and then maintain it as an external script; moreover, I do want to keep this coupled design for my polybar, everything in one helper script. This is a common situation, requirements change when you want to share and distribute, you quickly get into overengineering and overabstracting. But a quick textual suggestion with an accompanying code snippet, while lazy, allows others to adapt it to their own requirements.

**Comment by patrick96** [comment]
@memeplex I totally understand the intention, but if it lives on our wiki, it's not zero-maintenance. We will get issues about it from people struggling to get things to work.

We will not have such a page on our wiki. But we would of course welcome it if someone from the outside would maintain such a wiki.

**Comment by memeplex** [comment]
I understand yours too. I'm closing the issue for now, thanks!
