### ISSUE TITLE
[battery module] battery not detected

### ISSUE THREAD

**Issue by JaumeCarter** [jaagr/polybar#1655]
When i installed manjaro openbox i see that there's no battery status icon.
I tried a lot of things (people in manjaro forum help me) but nothing works.

If i try 
`polybar -r openbox-bar`
it returns me
`Disabling module “battery” (reason: No suitable way to get current capacity value)`
And when I use
`ls -1 /sys/class/power_supply/`
Only returns “ADP0” (The adapter name), but there’s nothing similar to the battery…

The output of `acpi -ab` it's `Adapter 0: off-line`, even if I open /etc/default/grub and add `acpi=force`.

We also try to use `udevadm monitor --property` and unplug-plug the power cord but nothing happens.

If someone know what can i do, please, help me.

**Comment by jstamant** [comment]
If your battery does not show up in `/sys/class/power_supply/`, then the battery module can't read it. As it stands, polybar's battery module requires the files/folder structure located in `/sys/class/power_supply/*` for its readings, so if there's nothing there, then the battery module won't do much for you.

I think you're on the right path though, looking into `udev`. I'm no expert, but I think `udev` needs to generate the device information in `/sys` when it sees your battery. I couldn't find any `udev` rules on my system that relate to the AC adapter, or the batteries, though. I saw somewhere that the Linux kernel might handle it. I'm running Arch, myself.

**Comment by patrick96** [comment]
@jstamant Thanks for helping out :)

Indeed, if there is no battery under `/sys/class/power_supply/` this really isn't polybar related and a deeper problem with your system (especially since not even `acpi` can read the battery information).

Since asking in the manjaro forums didn't help, I'd suggest looking for places that exist specifically for your laptop model (or at least manufacturer). It is possible that this is a hardware issue and not entirely a software issue. It is also possible that there isn't a way to get this kind of battery info into `/sys/class/power_supply/` at all (maybe for lack of a good driver).
