### ISSUE TITLE
Font Problems

### ISSUE THREAD

**Issue by fwanky** [jaagr/polybar#1714]
Long story short, I accidentally deleted my whole .config as well as my backups, wow, how? i don't know either

But basically now i'm rebuilding all of my configs which is horrible, but yeah

my main font looks really weird and squished? 
https://i.imgur.com/1CQADo9.png

Here's my font configuration in my config 
```
font-0 = Iosevka:style=Regular:pixelsize=8; 2
font-1 = "Font Awesome 5 Free:style=Regular:pixelsize=12;2"
font-2 = "Font Awesome 5 Free:style=Solid:pixelsize=12;2"
font-3 = "Font Awesome 5 Brands:style=Regular:pixelsize=12;2"
font-4 = cryptocoins:style=Regular8; 2
```

I don't get any errors about the font

https://pastebin.com/sa1WpV67

**Comment by patrick96** [comment]
I don't really see anything wrong in your screenshot, but it's very low quality, so that might be the reason.

Can you use polybar's built-in `--png` commandline argument to take a screenshot of the bar and post that. Also try to run polybar with the `info` log level and post the output of that, this will tell us if all the fonts were loaded.

In the future, please read our  read our [Support page](https://github.com/jaagr/polybar/blob/master/SUPPORT.md) for a list of resources where you can ask questions like these. The issue tracker is meant more for bugs.

**Comment by fwanky** [comment]
Fixed this myself, I appreicate the help though x

**Comment by redex557** [comment]
> Fixed this myself, I appreicate the help though x
Next time please mention how you fixed something!
