### ISSUE TITLE
Error 1 building bar.cpp.o

### ISSUE THREAD

**Issue by nwam** [jaagr/polybar#1721]
## Build Process
*Describe how you build polybar, list the exact commands you are using:*
```
cmake -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" ..
make
```
I've also tried `cmake ..`.

**If you build polybar directly from this repository:**
I've tried the repo version and 3.3.0, but my output is from version 3.2.1.
I've downgraded my xcb-proto from 1.12 to 1.11 and got the same results.

## Build Log
Here are my outputs from [cmake](https://gist.github.com/nwam/f4a8f32db598d2cd6038cfb66804bb75) and [make](https://gist.github.com/nwam/4016b9482afcb9fcdc18f4d7643d8683).

## Environment:
* Distro (with Version): Debian Stretch

**Comment by patrick96** [comment]
In your case downgrading xcb-proto will probably do more harm than good because your xcb-randr and xcb-proto version already match.

One thing you should try is to run the following in the root of the project:

```
rm lib/xpp/include/xpp/proto/*
```

This will remove all files generated by the xpp submodule. Regenerating these files often helps with these kinds of issues because your system configuration might have changed since you first generated them. Another thing, which has the same effect is to try to clone the git repo in a new location and build there, this will make sure that building a clean version actually doesn't work. Also please build either in the `3.3` branch or `master` so we know that you don't experience something we already fixed.

Please post the build output of this (and make sure you are again using xcb-proto 1.12)

**Comment by nwam** [comment]
Here is the output of [make](https://gist.github.com/nwam/be382a47554eb58c88fce592914706b1) on version 3.3, with xcb-proto 1.13 (turns out it wasn't 1.12) after removing `lib/xpp/include/xpp/proto/*` from the project root.

(the error seems to be the same)

**Comment by patrick96** [comment]
Are you sure you removed everything from `lib/xpp/include/xpp/proto/`? Your `make` output doesn't indicate that any file in the xpp submodule have been generated.

So xcb-proto is version 1.13 and xcb-randr is version 1.12?

**Comment by nwam** [comment]
Sorry about that, I think that I reran it without re-deleting. Here is the [output](https://gist.github.com/nwam/ce223b56014f05e8d3457bc7ee07506b) with the deletions.
And yes my xcb-proto is 1.13 and xcb-rander is 1.12.

**Comment by patrick96** [comment]
The version mismatch might be the problem then. How did you get xcb-proto 1.13? The [debian repos](https://packages.debian.org/stretch/xcb-proto) only have 1.12. I'd recommend downgrading to 1.12

**Comment by nwam** [comment]
Downgrading to 1.12 as outlined in #644 did the job! Thank you very much! 

Just waiting for the build to finish

**Comment by patrick96** [comment]
Great!
Did you manually build xcb-proto 1.12?

**Comment by nwam** [comment]
Yes, I grabbed it from [here](https://launchpad.net/ubuntu/+source/xcb-proto/1.12-1) and patched it with 1.12-1, then built and installed.

**Comment by patrick96** [comment]
You have to be careful with that since those are the ubuntu sources, they may not work on debian and break your system. 1.12 is also in the [debian repos](https://packages.debian.org/stretch/xcb-proto) and if you are not on testing or unstable, it even is the latest version.

**Comment by nwam** [comment]
Thanks for the heads up! I'm on a Debian Stretch fork where xcb-proto 1.12 isn't available through apt, but I'll keep that in mind and change over to the Debian source in the meantime.
