### ISSUE TITLE
Is it possible to bind click actions to the network module? 

### ISSUE THREAD

**Issue by Chrysostomus** [jaagr/polybar#233]
I would like to make network icon open networkmanager-dmenu or terminal with nmtui when clicked. How does one do this with polybar?

**Comment by jaagr** [comment]
Currently you would have to use raw tags to do this, for example:

~~~ dosini
[module/wlan]
...
format-disconnected = %{A:nm-connection-editor&:}disconnected%{A}
...
~~~

**Comment by Chrysostomus** [comment]
Okay, so the tag is just passed to the lemonbar. Many thanks!

**Comment by jaagr** [comment]
Lemonbar is not used anymore but lemonbar tags are supported.

**Comment by denysvitali** [comment]
@jaagr Sorry for necro-bumping the issue - but is the `click-left` option planned for the `internal/network` module?  
  
Raw tags seem to be an hackish way to accomplish the goal

**Comment by denysvitali** [comment]
Oh I see.  
I thought it was a hacky way to achieve the same goal because `click-left` seems to be available in all the other modules I've tested. But again, as long as it isn't a hack I'm good with it. It just doesn't look __that__ pretty in the config, but it is understandable, therefore I wouldn't consider it an issue.  
  
Thank you!
