### ISSUE TITLE
Polybar only shows up on current and empty workspaces on startup

### ISSUE THREAD

**Issue by quite** [jaagr/polybar#250]
With `wm_stack = bspwm` and `override-redirect = false`, polybar only manages to show up on the current workspace, and on workspaces which are empty.

On other workspaces -- which during this test has 1 sole client covering the whole screen -- the bar doesn't show up. But, if I turn on monocle mode in bspwm, the bar bumps into place.

 (To "reset the strut" while testing, I do `bspc config bottom_padding 1` after killing polybar)

I'm thinking now that this might even be a bug in bspwm...

**Comment by jaagr** [comment]
The config option should be `wm-restack = bspwm`. And the issue is caused by bspwm itself, but I saw a patch released a few days ago so make sure you are building against master.

**Comment by quite** [comment]
Yeah I read that, and I'm on bspwm master. wm-restack doesn't do it. But my
luck is slim... Should bring this to bspwm perhaps.

**Comment by jaagr** [comment]
I might add that `wm-restack = bspwm` actually moves the window down in the stack, making it appear behind other windows, and because bspwm doesn't apply the strut to all workspaces you can't see it (unless you use padding).

A workaround is to trigger an update on each desktop after launching polybar, making bspwm apply the strut to all desktops. 

~~~ sh
bspc query -D | while read -r desktop; do
  for side in top bottom left right; do
    bspc config -d ${desktop} ${side}_padding 0
  done
done
~~~
