### ISSUE TITLE
i3 show unused workspaces

### ISSUE THREAD

**Issue by eoli3n** [jaagr/polybar#274]
In your exemple, i see that you display unused workspaces.
How to show all i3 workspaces, even unused ?

http://i.imgur.com/A6spiZZ.png

**Comment by jaagr** [comment]
It's not possible using i3.

**Comment by eoli3n** [comment]
https://github.com/Airblader/i3/issues/117

**Comment by kenogo** [comment]
I have a pretty hacky solution that makes this possible without changes to i3. I used the `struct workspace_t`'s `output` entry (I figured displaying different things on different output devices is unnecessary in this use case, so I could just abuse the struct's `output` for something else without having to rewrite tons of code). Basically, I added a function that iterates through an array of set length and checks if the workspace number is equal to the index+1. If it isn't, it adds a workspace at this index and writes `"empty"` into `ws.output`. Later on, you can then add a check for this `"empty"` and add config options for a new window state called `empty`, which you can edit with `label-empty` and so on. This is needed in order to display a difference between an unfocused workspace and a non-existant workspace.

I don't think this hacky stuff deserves a pull request. But I can clean up a bit later and put some diffs here if there's interest for it.

**Comment by kenogo** [comment]
Anyone who wants this feature can use [this branch on my fork](https://github.com/kenogo/polybar/tree/i3-empty-workspaces). It adds a new workspace state called `state::EMPTY`. The configuration parameters are:

```
[module/i3]
ws-num = 6 ; Number of workspaces to display
show-all = true; Display all workspaces (even when there isn't a window open)
; use a different color to distinguish empty workspaces from unactive workspaces
label-empty-foreground = ${colors.foreground-alt}
label-empty = %icon%
```

**Comment by SippieCup** [comment]
@kenogo 

Just tried your branch and it works like a charm, cant wait to see it merged into the next release. 

offtopic: I finally got fed up not having unused workspaces enough just now to fix my config for the first time - to find that you just updated a stale year old issue 3 days ago with the solution. Thanks for the awesome work!

**Comment by kenogo** [comment]
@SippieCup Thank you, you're welcome :) I'll try to keep the branch up to date with coming polybar commits, but I don't think this branch is merge-worthy, because

1) It's quite a hacky solution that abuses the variable used to specify the monitor for its purpose (this is why this won't work if you want to display different workspaces in the bar on different monitors)
2) Not abusing this variable would mean needing to rewrite a lot of code (And I probably can't do this, since I don't even know C++)
3) These workspaces are not actually a feature of i3, so it's questionable whether polybar really wants to add this.

I could still create a pull request for this branch to ask the maintainer what they think of this feature, but I doubt they're ever going to merge this.

**Comment by vladdoster** [comment]
Did this ever get merged?

**Comment by patrick96** [comment]
> Did this ever get merged?

No. i3 doesn't have unused workspaces, so the i3 module should not attempt to display them.

**Comment by siduck76** [comment]
where's the branch? did you remove it

**Comment by vladdoster** [comment]
@siduck76 

> where's the branch? did you remove it

They removed the repository.

**Comment by Syzygianinfern0** [comment]
@kenogo do you have the fork saved elsewhere?

**Comment by vladdoster** [comment]
@Syzygianinfern0 https://github.com/i3/i3/pull/4311
