### ISSUE TITLE
Cannot compile latest version

### ISSUE THREAD

**Issue by alekcacko** [jaagr/polybar#344]
I cannot compile the latest version and I don't know why.

Using Ubuntu 16.04

Build log: http://pastebin.com/rwRuW5R9

**Comment by ChoiZ** [comment]
During debugging I use this package:
https://www.ubuntuupdates.org/package/getdeb_apps/yakkety/apps/getdeb/polybar

But there is no i3 support 👎

**Comment by alekcacko** [comment]
Yeah, I installed that too, but it is an older version too.

**Comment by jaagr** [comment]
Disable XRandR monitor support and it should work:

~~~ sh
$ cmake -DENABLE_XRANDR_MONITORS=0 ..
~~~

**Comment by ChoiZ** [comment]
It's works like a charm. Thanks @jaagr.

**Comment by alekcacko** [comment]
Thank you @jaagr . But what if I want to enable it?

**Comment by alekcacko** [comment]
Will you update the build script with randr disabled?

**Comment by jaagr** [comment]
@alekcacko what build script?

**Comment by alekcacko** [comment]
Your build.sh?

**Comment by jaagr** [comment]
cmake should disable it if the xrandr version is too old.. what does this command print?

~~~ sh
$ pkg-config xrandr ">= 1.5.0" --print-provides
~~~

**Comment by IrishPrime** [comment]
On Fedora 24, had the same issue with commit `9d589fa5a71f081aecfa455a9996904e458c8cfa`.

```
$ pkg-config xrandr ">= 1.5.0" --print-provides
xrandr = 1.5.1
```

**Comment by jaagr** [comment]
@IrishPrime Could you pastebin CMakeCache.txt in your build dir

**Comment by jaagr** [comment]
And could you also check:

~~~ sh
$ pkg-config randrproto ">= 1.5.0" --print-provides
~~~

**Comment by IrishPrime** [comment]
[CMakeCache.txt](http://pastebin.com/pWZuFMD1)

```
pkg-config randrproto ">= 1.5.0" --print-provides
randrproto = 1.5.0
```

**Comment by jaagr** [comment]
Can't see how you can get the error with `ENABLE_XRANDR_MONITORS:UNINITIALIZED=0`

**Comment by IrishPrime** [comment]
Yeah, I just realized that. I stupidly made the paste from my most recent build (using the workaround). Here's a [failing one](http://pastebin.com/DCHGzWjy) from the latest commit.

**Comment by jaagr** [comment]
This is probably why `XCBPROTO_VERSION:INTERNAL=1.11`.. It requires `1.12` if I'm not mistaken. Will add a check for that as well.

**Comment by hidde-jan** [comment]
This is still a problem on ubuntu 16.04. I've tried all different variations of -DWITH_XRANR_MONITORS (and -DENABLE_XRANDR_MONITORS) I found floating around the different issues, but cmake still tries to build with xrandr support.

**Comment by florianbaer** [comment]
Was this command renamed? Is it now called `WITH_XRANDR_MONITORS`? Can somebody verify this?

**Comment by patrick96** [comment]
Yeah it was changed 43a17c3b3634f11bca1365217723a0461b5cc0b2, it's now called `WITH_XRANDR_MONITORS`

**Comment by phiho1609** [comment]
I take no responsibilty, if sth about this fix destroys anything. Trying at ur own risk:

So i had the same problem. Ubuntu 17.xx, polybar, and every try to make randr.cpp was throwing the error, that (i think it was) .get_monitors or sth, is not known, and everything stopped. I tried every Tag i could find (`WITH_XRANDR_MONITORS`, `DENABLE_XRANDR_MONITORS`...), nothing worked. So i found a not great, but at least working workaround. I searched for the randr.cpp file in the polybar directory. I opened the code and searched for the part where it said something like `#if <SOME_XRANDR_TAG_SEEN_ABOVE>` (i cant remember which tag it exactly was, but it was one of the above mentioned and at the lower part of the file). So i just commented the code which is in the `#if` part out with `/* if part */`.

Because the part which should not be executed, was somehow still accepted as used code, i made it unused manually.

After that make the whole thing just with `cmake ..` (dont even have to use a tag, because code isnt active anymore), and it should work. When i execute the example bar, i get some errors and warnings, which seem not directly related to the 'fix', but maybe they are in some way, i just dont know.

Maybe it will help you as much as it did for me.
