### ISSUE TITLE
Font size discrepancy

### ISSUE THREAD

**Issue by Orion314** [jaagr/polybar#376]
It's not an issue per se, but after the last update (a few hours ago as of this writing) the font of my polybar got bigger somehow? I didn't touch the config for a while now, and I couldn't find anything of sort in the recent commits so I'm basically asking a question here.

The font was definitely smaller prior to the update, because the top bar used to fit on the screen, now some parts are going off screen (going over the upper border)

**Comment by israelss** [comment]
I had to change my font settings after last update, not because it was bigger, but because it was with an wrong offset, so the icons and text were going off-screen too..

E.g., I changed from:
`font-1 = fontawesome:size=10;0`
to:
`font-1 = fontawesome:size=10;3`

I don't know if you have already discarded that option, but take a look if you didn't.

**Comment by jaagr** [comment]
A few patches (e7dc6b8 and d2eeac9) changed the font rendering, to properly scale the fonts and to fix the vertical alignment. Just reset all vertical offsets to 0 (then tweak to center) and decrease the size a bit.

**Comment by Orion314** [comment]
That does it, thanks to both of you!

I should've combed through the commits a bit more attentively, apologies for that.
