### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by noonien** [jaagr/polybar#447]
Is there any chance we can get debian packaging? Would love to have a deb for my ubuntu machine.

I've not used cmake for quite some time, but I believe it can generate debs.

**Comment by jpleau** [comment]
I had a look at creating an official Debian package for this, but unfortunately there are a few things that are making this impossible right now. 

The biggest problem is that the lib/ directory is a complete mess... there are git submodules, 3rd party libraries, and a tarball. During build time on Debian (and Ubuntu) servers, we have to assume that internet is turned off (can't download anything)

I'll keep an eye on this, maybe @jaagr has an idea on how to make the lib/ directory more pretty :)

Since a lot of people seem interested in this project I will open a ticket on Debian mentionning my intentions on packaging it.

**Comment by noonien** [comment]
Having polybar in the debian repositories would be nice, but I being able to build a deb myself would be pretty nice also.

**Comment by jaagr** [comment]
I have no experience at all with the debian package system so I can't help much here. As for the lib directory I don't see any easy fix on how to clean it up and I don't have enough time on my hands at the moment to look into it.

**Comment by uggedal** [comment]
I have an unofficial package here: https://git.uggedal.com/pkg/polybar/

**Comment by patrick96** [comment]
Closing in favor of #1054
