### ISSUE TITLE
Ubuntu build issues & README proposal

### ISSUE THREAD

**Issue by Shippage** [jaagr/polybar#495]
I'm still getting a grasp of Linux, so trying to follow the instructions verbatim caused me some issues. I finally found a fix, and would request a change to the README install instructions, since I believe it's out of date.

`git clone --branch 3.0.4 --recursive https://github.com/jaagr/polybar`
This caused me some build issues, running branch 3.0.4 is outdated and does include the 'example' polybar config. Just cloning the latest version fixed this for me.

The command
`sudo apt install cmake cmake-data libcairo2-dev libxcb1-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-randr0-dev libxcb-util0-dev libxcb-xkb-dev pkg-config python-xcbgen xcb-proto libxcb-xrm-dev i3-wm libasound2-dev libmpdclient-dev libiw-dev libcurl4-openssl-dev`
fixed all the dependencies for me, and I think most people would benefit from this. Yet, it's hidden away on the wiki page. I propose this also get moved to the README.

**Comment by jaagr** [comment]
> [...] Just cloning the latest version fixed this for me.

I will create a new release tag to bump the version to 3.1.0 to fix the out-of-date tag.

> [...] Yet, it's hidden away on the wiki page. I propose this also get moved to the README.

I prefer having the distro specific build instructions on the wiki since it's writeable by everyone, so you could just edit it yourself and add the missing packages. A move to the README would require a pull-request merge for every change.
