### ISSUE TITLE
Issue with polybar autostart

### ISSUE THREAD

**Issue by Mofiqul** [jaagr/polybar#507]
while using i3 my polybar was starting fine at autostart but after installing i3-gaps it was not starting.
The problem is solve by putting  
`sleep 0.01` after` killall -q i3bar `

**Comment by jaagr** [comment]
Are you using polybar and i3bar?

**Comment by Mofiqul** [comment]
I am using polybar. the problem was not as I mentioned above. when rebooted my computer last time my polybar was not stared. Now its fine though but only after executing polybar first

```
exec --no-startup-id $HOME/.config/polybar/polybar_launch.sh &
exec killall i3bar
exec --no-startup-id nitrogen --restore  &
#exec --no-startup-id redshift  &
exec --no-startup-id compton --config ~/.compton.conf -b 
exec --no-startup-id dunst -config $HOME/.config/dunst/dunstrc
#exec --no-startup-id $HOME/.local/bin/barstart &
#exec --no-startup-id conky -c $HOME/.config/i3/conkybar-bottom &
#exec --no-startup-id conky -c $HOME/.config/i3/conkybar-top &
exec --no-startup-id xrdb -merge -I$HOME ~/.Xresources


```
when i puted the polybar script at first line with the killall i3bar it working now, without killall i3bar does not work again

**Comment by jaagr** [comment]
Why are you launching i3bar if you're​ not using it? You could probably just comment out the bar section in your i3 config to avoid launching i3bar.

**Comment by Mofiqul** [comment]
Yap.. I did not thought about that.. its fine now. thanks.

**Comment by jaagr** [comment]
Great! I'll close the issue for now then, please re-open if you experience any other issue with it.

**Comment by llomellamomario** [comment]
I do experience the samme issue, in fact, what is even more strange when restarting i3 gaps in place it starts all bars as expected. No i3blocks anywhere on my file, the only thing that changes from the wiki page is that I am booting two bars, one for each monitor. Trying to launch one bar results in pretty much the same results. I know for a fact that the file is getting executed, since a touch command after the bar commands shows the file after login, the problem seems to be localized to polybar launching at start on i3gaps. Any clue where the problem could lie?

**Comment by Rantahu** [comment]
@llomellamomario I'm having the same issue. Polybar example doesn't even work

**Comment by dylanarmstrong** [comment]
I'm having this issue while using i3-gaps as well. Polybar will start from a terminal, but not when starting from i3-gaps.

**Comment by AUTplayed** [comment]
@llomellamomario I have the same issue, did you find a fix?
