### ISSUE TITLE
MPD showing untitled artist - untitled song, while mpc does show right values

### ISSUE THREAD

**Issue by Jesse-Bakker** [jaagr/polybar#509]
My polybar shows just: `untitled artist - untitled track` instead of the artist and track name.
Logs show nothing and mpc works fine with the same connection settings.

**Comment by jaagr** [comment]
Did you solve the issue?

**Comment by imdyske** [comment]
I have the very same issue. Polybar's MPD module shows 'untitled track' *(and artist,... depending on `label-song`)*, while `mpc` shows the correct song information. It happens only when mpd is playing a playlist from Soundcloud. There isn't anything in logs, therefore `mpd_exception` on https://github.com/jaagr/polybar/blob/master/src/modules/mpd.cpp#L215 isn't thrown. And while artist and album should be empty *(since they are loaded from SC)* the track name should not *(according to `mpc`)*.
Steps to reproduce:
Enable soundcloud playlist plugin in mpd config i.e.
```
playlist_plugin {
    name "soundcloud"
    enabled "true"
}
```
and restart mpd. Then simply load playlist via mpc: `mpc load 'soundcloud://url/mrteddy_us/sets/zen'`
