### ISSUE TITLE
Space on modules's bottom

### ISSUE THREAD

**Issue by matjaz132** [jaagr/polybar#514]
There is a reserved space on bottom of the modules where the underline goes. Even if it's disabled there is still some space/margin. How do I disable this?

**Comment by gnubeest** [comment]
Another side-effect is that workspace indicator backgrounds actually fill this space, which makes them longer underneath the text than at the top. This is weirdly worked around by setting line-size to 4 and giving them an underline the same color as the bar background; because of the aforementioned "reserved space", the bar ends up having the same gap anyway as it would if line-size was set to 0.

**Comment by jaagr** [comment]
Have you tried changing the vertical offset of the font you are using? You can lower the text/icons that way. More information on the wiki.

**Comment by matjaz132** [comment]
Thank you! Font vertical settings work perfectly :+1:

**Comment by jaagr** [comment]
Great!
