### ISSUE TITLE
used memory module wrong

### ISSUE THREAD

**Issue by MaxNeutrino** [jaagr/polybar#518]
Why `free -m` and `screenfetch` display 197 mb used, but memory module with settings 
`type = internal/memory`
`interval = 2`
`format-prefix = " "`
`format-prefix-foreground = ${colors.foreground}`
`label = %mb_used%`
display 406 mb used

**Comment by jaagr** [comment]
The `%mb_used%` token will display `MemTotal-MemAvailable` so when checking `free -m` you'd also have to consider the `buff/cache` column. The semantics of the `_used` suffix is however debatable.

**Comment by nico202** [comment]
As a reference I found useful about memory on unix: https://jvns.ca/blog/2016/12/03/how-much-memory-is-my-process-using-/

Il 5 aprile 2017 20:34:08 CEST, Michael Carlberg <notifications@github.com> ha scritto:
>The `%mb_used%` token will display `MemTotal-MemAvailable` so when
>checking `free -m` you'd also have to consider the `buff/cache` column.
>The semantics of the `_used` suffix is however debatable.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jaagr/polybar/issues/518#issuecomment-291954625

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by x70b1** [comment]
A bit more of information about memory usage:
http://www.linuxatemyram.com/

polybar shows what I expected. There are also inaccuracies due to rounding.

Additionaly there is the Binary prefix problem (1000 or 1024?). You could look at `free --si`. Now you have another different output.

I guess there is no "correct" value. It is more important to know how the displayed value was calculated. 
We could add something in the wiki. But I think this is too common to left words about it.
