### ISSUE TITLE
KeePass (Mono edition) not appearing in systray but outside

### ISSUE THREAD

**Issue by oschoudhury** [jaagr/polybar#545]
I am running Polybar version 3.0.5 on top of i3 (v4.13). All my tray icons appear in the systray in the bottom right except for KeePass ([default Arch edition](https://www.archlinux.org/packages/community/any/keepass/)). The KeePass tray icon instead appears in the upper left corner of my screen, as can be seen in the following screenshot. I am not using any other programs that run on the Mono platform, so I can't tell whether it is KeePass or Mono that is acting different.

![keepass-corner-tray-icon](https://cloud.githubusercontent.com/assets/5940021/25229606/3416e018-25d1-11e7-9f93-1a444af89e55.png)

**Comment by oschoudhury** [comment]
I forgot to mention in the original post that the icon does not appear at all after starting KeePass (in contrast to what I have seen in KDE where it appears immediately). The icon only appears after I reload i3.

**Comment by UnicodeAlt255** [comment]
This persists after killall polybar.

**Comment by mattoufoutu** [comment]
I'm having the same problem. I see this issue has been open since april, is there anything new regarding it? Is there something that could be done to help investigate?

**Comment by NBonaparte** [comment]
Unfortunately, this appears to be a mono issue, because WinForms tray support is broken. There isn't anything that we can do on our side. Try using [keepass2-plugin-tray-icon](https://aur.archlinux.org/packages/keepass2-plugin-tray-icon/) in the AUR, which uses [Keebuntu](https://github.com/dlech/Keebuntu) to create a working tray icon.
