### ISSUE TITLE
Wifi ramp signal problem

### ISSUE THREAD

**Issue by SnakeS22** [jaagr/polybar#548]
Hi there,
I'm having touble configuring wifi signal levels (I mean using mutiple icons for signal quality)
%signal% is always 0 therefore Polybar always shows ramp-signal-0
but %essid% works currectly
thanks for reading ;)

**Comment by jaagr** [comment]
Hi, please see the comment at #402

**Comment by SnakeS22** [comment]
Thanks ;)

**Comment by Staberinde** [comment]
I'm getting the same issue with a Broadcom Limited BCM4352 802.11ac Wireless Network Adapter running Ubuntu 18.04, despite `iwlist scan` giving me a value for signal quality:
```
wlp6s0    Scan completed :
          Cell 01 - Address: 48:D3:43:52:FA:19
                    Channel:6
                    Frequency:2.437 GHz (Channel 6)
                    Quality=56/70  Signal level=-54 dBm
 ```
Looking around online it looks like the `/sys/class/net/wlp6s0/wireless` directory should contain a file-like object called `link` that can be read to get a value for signal strength. However my `/sys/class/net/wlp6s0/wireless` directory is empty, even though `cat /sys/class/net/wlp6s0/carrier` returns 1 and `iwconfig` confirms that `wlp6so` confirms that this network adapter is wireless.

My guess would be that there's more than one interface for wireless signal strength, and that my wireless drivers are populating a different signal strength interface to the one that polybar is looking for, and polybar is returning a zero value because it cannot find that signal strength interface.

Hope this helps someone with the same issue. I'll update with any further progress.

**Comment by patrick96** [comment]
@Staberinde Does `polybar -vvv` show ` +network(libnl)` or ` +network(wireless_tools)`? If it shows the former, please open a new issue, because we have moved away from wireless_tools and the data you should be comparing to are the ones from `iw dev wlp6s0 station dump`.
