### ISSUE TITLE
Problem with Format tags and Custom Variables

### ISSUE THREAD

**Issue by N4d4** [jaagr/polybar#615]
Custom Variables doesn't work in Format Tag
I need to change this...
![before](https://user-images.githubusercontent.com/19915501/27013931-b2d49d88-4eed-11e7-83ac-86ab395970a7.png)
`label-active = %{B#5a000000 F#333}%{F- B#333}%{o#924} %icon% %{B#5a000000 F#333}%{F- B- -o}`

in something like this...
`label-active = %{B${colors.black} F${colors.grey}}%{F- B${colors.grey}}%{o${colors.red}} %icon% %{B${colors.black} F${colors.grey}}%{F- B- -o}`

as you can see it doesn't work
![after](https://user-images.githubusercontent.com/19915501/27013924-9f3ccba6-4eed-11e7-94f9-bd5c43bf616d.png)

there is a way to make it work properly?

**Comment by NBonaparte** [comment]
This isn't possible because of how the config parser works.

**Comment by johnhamelink** [comment]
Just a quick note for anyone researching this: it is possible to use custom variables with prefixes in order to have a different colours. You can't interpolate values, but if you want to have a different coloured icon for your temperature, you can do it this way:

As an example:
```
[module/github]
type = internal/github
token = ${env:POLYBAR_GITHUB_ACCESS_TOKEN}
user = johnhamelink
interval = 10
format-prefix-foreground = ${colors.foreground-alt}
format-prefix = "%{T5}!%{T-} " ; Use the "github-octicons" font, the `!` symbol produces the github icon
label =  %notifications%
```

Produces something like this:

![out](https://user-images.githubusercontent.com/101739/96338147-1345c880-1084-11eb-8a82-6bec7e08dbdb.png)
