### ISSUE TITLE
Polybar linux mint/ubuntu install [i3]

### ISSUE THREAD

**Issue by JarrColl** [jaagr/polybar#618]
Is their any way to install polybar on ubuntu without compiling from source?

**Comment by jaagr** [comment]
Depends on what version you are using.

**Comment by JarrColl** [comment]
The newest Linux mint which I think runs Ubuntu 16.04

**Comment by patrick96** [comment]
Linux Mint is its own linux distribution and is not Ubuntu, though it is based on it. I don't know that much about it, but it probably can install packages meant for ubuntu. I have found a packaged version of polybar [here](https://www.ubuntuupdates.org/pm/polybar). Since this is from an external PPA, you'll need to install the [getdeb](http://www.getdeb.net/updates/Ubuntu/16.04) repository first.
