### ISSUE TITLE
Linking in Makefile Fails

### ISSUE THREAD

**Issue by jmittelstaedt** [jaagr/polybar#628]
Hi,

I've had a lot of trouble making polybar. When doing
`sudo make install`
it gets to about 95% completed and then fails, with almost all of the errors being "undefined reference to ..." all of these errors are in [make_log.txt](https://github.com/jaagr/polybar/files/1116616/make_log.txt) (it's pretty huge because there are a lot of errors). I have double checked that I have all the dependencies, the only thing that I found that may be a problem is that on the apt repository, libjsoncpp is version ~1.2, but during the cmake part there's something which seems like it was able to take care of it, this is near the end of [cmake_log.txt](https://github.com/jaagr/polybar/files/1116619/cmake_log.txt). I'm running GalliumOS 2.0, which is basically Xubuntu/Ubuntu Xenial. Any help with what may be going wrong would be appreciated!

**Comment by patrick96** [comment]
The message about `jsoncpp` is because the (i3ipcpp)[https://github.com/jaagr/i3ipcpp/tree/8ed783100bbc8053fd7d8e19cef58cd097ff23f7] module will build `jsoncpp` from source if it is not found on your system. But the beginning of your `make_log.txt` seems to indicate that for that was successful.

From google I get the errors are because it is not linking against the standard libraries. I'm not that experienced in that area but I have some tips (totally remove the build directory before trying any of these).

1. **Manually set linker flags**
Run the following cmake command: `cmake -DCXXLIB_CLANG=ON ..` instead of just `cmake ..`

Or

2. **Run the build script provided in the repo**
In the root of the repo is a `build.sh` script, it does some setup for you and sets additional cmake flags, just running this will compile and install polybar.

Also be sure to capture the logs when you try any of these.

**Comment by jmittelstaedt** [comment]
Hi @patrick96, after poking around a bit I think my problem ended up being with the compiler I was using. I had installed and was using clang-3.8 from the Ubuntu package repository which was giving some strange errors, saying it didn't have some standard libraries. I have since switched to some version of gcc and everything worked! Thanks for the help.
