### ISSUE TITLE
Once the exec-if condition goes from true to false, the module does not end

### ISSUE THREAD

**Issue by Honnou** [jaagr/polybar#634]
I'm currently experimenting with a script I made that echoes the song that is being played in spotify using playerctl, which I got working. In the config the module is configured as follows:
```
[module/spotifytitle]
type = custom/script
exec = ./.config/polybar/modules/spotify.sh 35
exec-if = pgrep -x spotify
label = %{T2}%{T1} %output%
tail = true
interval = 0
```

If I restart polybar it works fine, no module is shown. If I then start spotify the module appears:
![screenshot_2017-07-04_10-23-26](https://user-images.githubusercontent.com/1879915/27861074-8fbccb5a-617f-11e7-90f1-43d64f203ca4.png)
![screenshot_2017-07-05_12-43-58](https://user-images.githubusercontent.com/1879915/27861148-dd30aeb0-617f-11e7-9835-4b9c1b012d85.png)
![screenshot_2017-07-05_12-44-06](https://user-images.githubusercontent.com/1879915/27861191-10ba2bd0-6180-11e7-93af-c2baf9f65879.png)

Once I stop spotify, the third image occurs, the module persists, which I hoped it wouldn't. 
`pgrep -x spotify`
returns nothing, so I know for sure that no instance of spotify runs and the -x flag prevents confusion between spotify and spotify.sh. 

So my intention is for the module to disappear once spotify shuts down. Is polybar not doing this 'work as intended', is it a bug or am I doing something wrong myself?

NOTE: I fixed this locally by making the script itself check for instances of spotify and then terminating if that returns false, but it'd be great if polybar itself did this.

**Comment by patrick96** [comment]
I think this has to do with the fact that you tail the script output. Because polybar now waits for the script to finish before it ever checks the `exec-if` condition again, and because your script probably has an infinite loop, it will never exit.

If you don't have a real reason to have an infinite loop in the `spotify.sh` script, I would recommend to remove it and set `tail = false`

I don't think this is a bug but rather by design, the bar would have to kill the `exec` process as soon as `exec-if` evaluates to false and that can get quite messy. I have added a note about this to the wiki

**Comment by Honnou** [comment]
@patrick96 the reason for me to tail the script is because the output scrolls once the string exceeds a number of characters. If this is how it works by design, then consider this issue closed :) 

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by patrick96** [comment]
That's an interesting usecase
If you want to keep relying on `exec-if`, you can terminate the script, as soon as both lines have been displayed. The bar will keep the module content on the bar and after `interval`  has passed it will evaluate `exec-if` before executing the script and if it returns false it will remove the module content
