### ISSUE TITLE
bar-progress-indicator-foreground in mpd module sets foreground of all following modules

### ISSUE THREAD

**Issue by Alexander-Miller** [jaagr/polybar#666]
Setting mpd's bar-progress-indicator-foreground currently sets the foreground color of any modules that follow: http://imgur.com/a/K2XcZ

Running polybar-git installed from the AUR on Antergos (not using stable due to the curl build issue).
Complete polybar config and the script I use to launch it can be found [here](https://github.com/Alexander-Miller/dotfiles/tree/master/.config/polybar).
Other than a warning about i3 restacking the log is quiet.

```
❯❯❯ polybar --version
polybar 3.0.5-26-g2d1e3c2

Features: +alsa +curl +i3 +mpd +network
```

**Comment by patrick96** [comment]
This bug was introduced in https://github.com/jaagr/polybar/commit/f754fa27103e0df9a10b0083babd7ad29605e016 and exists because the progressbar does not properly close the foreground color tags. This is what my progressbar looks like: 
```
 %{F#DE935F}━━━━━━━━━%{F#DE935F}━%{F#373B41}━━━━━%{F-}
```
I have described this issue in #639, with the color stacks, the foreground after that module is now `#373B41`. Though it is not clear whether needing to terminate the colors is intended behaviour. Until we get some feedback from @jaagr about the color stacks, I think we should just make do with temporary fixes.

For now the best course of action would be to just use the stable release (3.0.5) and manually fixing the curl issue by applying the patch in https://github.com/jaagr/polybar/commit/d35abc7620c8f06618b4708d9a969dfa2f309e96

Another temporary fix would be to insert a module that resets all the foreground tags directly after the mpd module so that subsequent modules start with the bar foreground:
```dosini
[module/reset]
type = custom/text
content = "%{F-}%{F-}%{F-}%{F-}%{F-}%{F-}"
```
This of course does not fix the wrong foreground colors inside the modules

**Comment by Alexander-Miller** [comment]
> For now the best course of action would be to just use the stable release (3.0.5) and manually fixing the curl issue 

Thanks for the explanation. I'll go with this for now.

**Comment by patrick96** [comment]
The root cause of this issue will be tracked in #639
