### ISSUE TITLE
Polybar top space on vertical monitor bspwm

### ISSUE THREAD

**Issue by blkob** [jaagr/polybar#677]
So I've been trying to setup polybar with bspwm and on my vertical monitor I get a lot of extra space from the bar down (applications start in lower half of the screen). Without starting polybar or without having it on that monitor, everything works just fine. Also, the landscape monitors work just fine.

[Configs](https://pastebin.com/fbkxkkXH)

**Comment by patrick96** [comment]
Can you show a screenshot of this behaviour, I'm not sure I totally understand what you mean. Also make sure the screenshot contains all monitors

**Comment by blkob** [comment]
Sorry for the long time. Here is a photo
![screen](https://user-images.githubusercontent.com/30492378/28770091-6ff45f1a-75cd-11e7-9ee0-b635dfe575af.jpg)
Please ignore the distorsions on the top of the screen :)

**Comment by patrick96** [comment]
Does this also happen, when you only start the polybar on the vertical monitor?
On the leftmost monitor, do you also have more extra space below the bar than you have on the middle monitor?
Try to play around with the values of `override-redirect` (`true`/`false`) and `wm-restack` (`bspwm`/NONE) since this is probably an issue with polybar interacting with bspwm.

**Comment by blkob** [comment]
Ok, I've figured out what causes the problem. Apparently the main bar's width is the culprit. I've had it set ad 98% with offset-x at 1%. For some reason setting it to 96% and 2% fixed the issue. I've played around with override-redirect and wm-restack but I still get the behavior.
I've also tried to kill compton but it still didn't work.
I think it may have to do with the resolution since I use an odd one (2160x912).

**Comment by patrick96** [comment]
This is most likely a rounding error, the offset and width percentages are converted to integer pixel values and because 1% of 2160 (or most other numbers) is not a whole number and some other quirks when you add up the pixel values for the offset and the width you get a number larger than before and this causes polybar to extend over to the other monitor.

It doesn't directly have to do with your resolution, it's just unlucky that this quirk shows for that number (if I got it right, it will also occur for 2560 pixels). To fix this you can try other percentages (you have already found 2% and 96%) or you could specify the offset and width in pixels (which would be less portable but more reliable). I also wanted to suggest using 0.9% as the offset and keep 98% width but I don't think polybar accepts floating point percentages.

**Comment by blkob** [comment]
Yea I've tried using floating point numbers in the bar before, but with no luck. That lead me to think it was a rounding error too. Thanks for the input.
