### ISSUE TITLE
Option to launch modules only when internet connection is present

### ISSUE THREAD

**Issue by binaryplease** [jaagr/polybar#692]
Hi,

Some modules throw errors when there is no internet connection. This does't look very nice.
It would be nice to be able to hide specific modules until an internet connection is present.
If there already is such an option it probably should be documented in the wiki.

Cheers!

**Comment by patrick96** [comment]
Which modules are that? If it's a script that is called from a script module then that script is itself responsible for handling its output. So it will either have to check if it is connected to the internet itself or handle connection errors in a way that does not just print the error message.

**Comment by binaryplease** [comment]
the cower module for archlinux updates, e.g. It's an user-contributed one though. I'll watch out if it happens on others too, just thought there could be a general option to not run them until connection is up instead of a per module one.

**Comment by patrick96** [comment]
All the user-contributed modules are just script modules calling an external script. You can already use the `exec-if` option to try to ping a website and only run the script, if the ping is successful (The ["Archlinux Updates"](https://github.com/jaagr/polybar/wiki/User-contributed-modules#archlinux-updates) module already does that).
Of course you can never be certain that the script will not throw an error because the connection may have dropped in between or some servers aren't reachable, but if the checking was built into polybar you couldn't be sure either.

I think it would still be best, if the scripts are able to properly handle errors themselves because there could be other kinds of errors than just connection issues and it's also just better design ;)
But adding the `exec-if` option will probably hide the bulk of the errors.

**Comment by patrick96** [comment]
Closing. This will most likely not be implemented in polybar and sufficient alternatives have been presented.
