### ISSUE TITLE
Script click and scroll output

### ISSUE THREAD

**Issue by Eyenseo** [jaagr/polybar#720]
I had a look at the issues but didn't find any that matched my issue, if this is already possible or was discussed before it would be nice if you could give me a link.

It would be very nice if the output of the click and scroll actions would be used by the label of the script module. With that the update interval could be higher while the click would feel more responsive.

**Comment by NBonaparte** [comment]
If I understood you correctly, this should be possible through the [ipc module](https://github.com/jaagr/polybar/wiki/Module:-ipc).

**Comment by Eyenseo** [comment]
As far as I can see the ipc module does not have the interval option, which I would still want. I suspect that going over ipc would be over complicated if the trigger is polybar itself.

**Comment by qqldd** [comment]
I vote for this. And this issue also requested for this:
https://github.com/jaagr/polybar/issues/84

**Comment by NBonaparte** [comment]
This looks to be the same issue as #786. Closing in favor of that issue, as its title is more descriptive. Please reopen if I misunderstood this issue.

**Comment by patrick96** [comment]
#786 wants the `exec` command to be rerun and this wants to display the output of the `click-*` commands inside the module.
I'm going to reopen this and add it to our TODO list

**Comment by patrick96** [comment]
Thinking about this a little more, the main motivation for this issue was to have scripts be more responsive, maybe because the click actions produce the same output as `exec` itself. If it's anything else I really don't see a use case for it other than visual feedback. But then there would be the issue of when does that output get removed from the bar.

Updating the script module on click will be implemented as requested in #786 any other use case will not be implemented
