### ISSUE TITLE
Change cursor on hover of clickable module?

### ISSUE THREAD

**Issue by AndreasBackx** [jaagr/polybar#721]
Would it be possible to change the cursor to a pointer when hovering a module? Perhaps even make it configurable like it is in CSS? It immediately provides feedback to the user that an item is clickable. I've got the following menu in my bar of which I'd love to know where the clickable areas are so I don't missclick:

![Polybar menu.](https://i.imgur.com/IglKEK9.png)

CSS offers a lot of keyword values that could be considered for this feature, this is documented on the [MDN](https://developer.mozilla.org/en/docs/Web/CSS/cursor). The following config is what I propose then, the exact same as CSS:

```ini
[module/menu]
cursor = pointer
```

**Comment by NBonaparte** [comment]
I think this would require another dependency, `xcb-util-cursor`, but otherwise it should be doable. The names used are slightly different though (see [here](https://cgit.freedesktop.org/xcb/util-cursor/tree/cursor/shape_to_id.gperf)), so we'd have to do some slight translation. 

Which cursors in particular would you like to have implemented? IMO most of them would be useless for this purpose except for the pointer.

**Comment by AndreasBackx** [comment]
I honestly have no idea what people would like to use. I feel like half of these are a bit odd to use on a bar. Would it be possible to allow for a string value which is then mapped to that list of possible values?

**Comment by NBonaparte** [comment]
Since the cursor names aren't actually standardized (which is a pain), we have to loop through the possible names anyways. It definitely will be easier to just adopt the CSS names.

For now, I think just the pointer is enough, and we can add more if anyone else requests them. 

Also, I'm considering just having the pointer as a global bar setting. Would that suffice?

**Comment by AndreasBackx** [comment]
What I would do, is to make the pointer the default cursor when hovering a module that has a clickable event set or a scrollable event. This indicates that the module is interactable.

I don't think a global bar setting would suffice as it wouldn't give the feedback that is mostly desired. For example when you hover over a link on a website, the pointer cursor and most of the time button CSS style indicates that what you are hovering can be clicked. It would look very odd to have a pointer cursor when hovering the whole bar.

But only having a pointer now is fine I guess. Maybe if it's not too much work, then the implementation could allow for easy adding of cursors? But only add pointer for now so you at least don't have to do any research on what will and what won't work perhaps? It's up to you.

**Comment by NBonaparte** [comment]
Sorry for the confusion, I meant to say what you just described (cursor change on every clickable area), but as a global setting in the bar (so _all_ clickable areas will change cursors).
I might exclude scrolling, as there isn't a special cursor for it (that I'm aware of).

**Comment by AndreasBackx** [comment]
Maybe we could add the setting to the bar, but allow people to disable/enable it as well explicitlyper module? I would personally also enable the pointer if there is a scroll event, better some indication than none I guess.

**Comment by NBonaparte** [comment]
I think we'll have `cursor-click` for click events and `cursor-scroll` for scroll events.

I'm reluctant to implement per-module settings, as that would require messing around with the builder and renderer and complicates things greatly.
