### ISSUE TITLE
Font issue in xmonad

### ISSUE THREAD

**Issue by MxLinux** [jaagr/polybar#751]
![2017-09-14-194956_2880x1800_scrot](https://user-images.githubusercontent.com/2219973/30460935-36ddb9fe-9988-11e7-9cfe-14d5f229d68e.png)

In the screenshot above the workspaces are displayed on the left of polybar. They should display as " ● " for ppCurrent, " ○ " for ppHidden and ppHiddenNoWindows, and as a red " ● " for ppUrgent. It all works as expected in xmobar but I really like the thought of having my tray and bar all in one go, and the ability to specify x/y positions (since I haven't been able to figure it out quite right with trayer). The issue is that for the active workspace instead of the filled in dot, it shows "342227217" and for hidden workspaces it shows "342227213". I've tried a few different fonts including Source Code Pro, Droid Sans Mono, and Droid Sans Fallback. Currently have 

`font-0 = "Droid Sans Fallback:pixelsize=11;0"
font-1 = FontAwesome:size=8;-1` 
in my polybar config for fonts

`myLogHook h = h
        {
            logHook = (logHook h) >> (dynamicLogString pp >>=xmonadPropLog)
        } where
        pp = def
            {
                ppCurrent =		\s -> " ● "
              , ppHidden =		\s -> " ○ "
              , ppHiddenNoWindows =	\s -> " ○ "
              , ppUrgent =		wrap "%{u#FF0000 +u" "%{-u}" . \s -> " ● "
              , ppOrder =		\(ws:_:_:_) -> [ws]
            }
`

is my xmonad hook for initiating workspaces in polybar. 

I don't really know much about fonts or how the programs are interacting so it may not be possible to do this currently but a chance for some insight is better than nothing.

**Comment by patrick96** [comment]
This is definitely not a font issue, those numbers seem to be the values of the binary representation of the font icons. Somehow either xmonad sends those characters in a way that polybar interprets as a string of digits or polybar reads this wrong.
Are you using the `xworkspaces` module for this?

**Comment by asturtz2** [comment]
I think I know the issue, and I don't think it is related to polybar. The number "342227213" you see there is the unicode for your "ppHidden" icon if you took the binary representation of the unicode, split it up into three equal parts, converted said parts into octal, and concatentated the resulting numbers.

The reason for this seemingly random behavior is that the unicode representation of that character requires 3 bytes, and `String`s are fundamentally a list of one-byte `Char`s. When you use `dynamicLogString` and `xmonadPropLog`, you are implicitly encoding the given string into a number in UTF-8 and then converting the resulting number back into a list of one-byte `Char`s (via a call to `encodeString` in `Codec.Binary.UTF8.String`), which, when displayed, displays their respective values in octal form, concatenated together.

Although I haven't personally tested it, I believe this can be solved using `Data.Text` instead of `String`. It is a data type designed to pack character bytes together so that, for example, it will know if the string is encoded in UTF-8 and can read it accordingly. `putStr` from the `Data.Text.IO` module can output correct UTF-8 strings to standard output, and there is additionally a wealth of other utilities and functions to accomplish just about anything you could want probably.

You can also accomplish most of what you want by just using polybar modules with no log hook, though there is no support for urgent/occupied workspaces as of yet. I use this method for my XMonad configuration, and it's pretty simple. All you need is the `EwmhDesktops` module from xmonad-contrib. Though I will say that looking into all this has me thinking I might look into writing my own custom log hook for polybar as well.

**Comment by japrogramer** [comment]
@MxLinux how did you get polybar to work with xmonad? can i see your hs file?

**Comment by kronn** [comment]
@MxLinux could you share your polybar and xmonad-configs somewhere? This sounds like something that can be turned into a wiki-page here to helps other (well, me, for starters), to integrate polybar and xmonad. The current integration "with any EWMH-compatible" WM is a start, but I feel like there is room for improvement.
