### ISSUE TITLE
Can I get the config for the bottom taskbar on the screenshot?

### ISSUE THREAD

**Issue by skullscream** [jaagr/polybar#777]
I only want the taskbar from the bottom on the screenshot but i don't get it launching the example config. Using lxde here on arch.

![xvlw9ih](https://user-images.githubusercontent.com/18366085/30780261-3851a86e-a107-11e7-8aae-1b11922e5d78.png)

Sorry for making an issue for this.

**Comment by patrick96** [comment]
See #690 for the config.
The module on the bottom left isn't really a task bar. It's a list of all workspaces and it uses a different icon per workspace. Also the config in #690 is for bspwm, since you use lxde, you would have to use the [`internal/xworkspaces`](https://github.com/jaagr/polybar/wiki/Module:-xworkspaces) module

**Comment by skullscream** [comment]
Never mind then. I just want a replacement taskbar that looks nice for that lxpanel.

**Comment by futterwaqckens** [comment]
Hi.... Is there away to scroll Mpris title?

**Comment by patrick96** [comment]
@futterwaqckens This has been discussed [here](https://www.reddit.com/r/Polybar/comments/8tp3t2/help_with_spotifyzscrollplayerctl_script/). But you need quite advanced shell scripting to achieve that.

**Comment by futterwaqckens** [comment]
I got it working by simply following the suggestions. :) now rhythmbox scrolls. Thank you.
