### ISSUE TITLE
Use environment variable to set font size

### ISSUE THREAD

**Issue by CarlosMChica** [jaagr/polybar#782]
Hi,

I've been using polybar for quite a while and it's simply the best out there!

I just have one issue that I haven't figure out how to do. I'm trying to set the font size by reading the value from an environment variable, but I can't get it to work.

E.g. I use it to define the bar height as follows:
 `height = ${env:POLYBAR_HEIGHT:40}` 
but I can't get it to work for the font size. I'm trying to do it as follows:
 `font-0 = xos4 Terminus:pixelsize=${env:POLYBAR_FONT_SIZE:20};2`

It seems to fall back to some default value as it does not matter what I set the environment variable POLYBAR_FONT_SIZE nor the fallback value afterwards.

Thanks a lot in advance.
A grateful user :)

**Comment by patrick96** [comment]
environment variable substitution only works, if the environment variable is the only thing that is assigned, it can't be part of a larger string. That's why assigning the height works but `font-0` doesn't.

The way I solved this in my config is by defining the whole font string inside bash:
```bash
export BAR_FONT_0="xos4 Terminus:pixelsize=${POLYBAR_FONT_SIZE:-20};2"
```

And then use that as the value for `font-0`:
```dosini
font-0 = ${env:BAR_FONT_0}
```

**Comment by CarlosMChica** [comment]
Thanks for your answer, got it working now :)

**Comment by CarlosMChica** [comment]
BTW probably worth adding to the wiki as I didn't seem to find this information there. Maybe I just missed it though.
