### ISSUE TITLE
Maxing out inotify watch

### ISSUE THREAD

**Issue by hshin23** [jaagr/polybar#805]
Note: This is potentially related to #469 

script I'm using for getting mpc info:
```
if ! mpc >/dev/null 2>&1; then
  echo Server offline
  exit 1
elif mpc status | grep -q playing; then
  mpc current | zscroll -l 52 -d 0.3 -n &
else
  echo Not playing
fi
# Block until an event is emitted
mpc idle >/dev/null
```

I noticed a bug with maxing out inotify watches,
and doing some further research, I noticed that this (in my case, strictly; may apply to others)
is due to multiple instances of zscroll running and not getting terminated.
This happens when a song is played with sufficiently long length of info to display.
Whenever a new song gets played, a different instance of zscroll is used, taking additional inotify instance,
in the end maxing out number of inotify watches.

Currently I'm doing `killall zscroll` to clear it.

Is there a way to kill zscroll instance after the song is done playing, or after the song is skipped?

**Comment by patrick96** [comment]
What are the parent processes of the running `zscroll` instances? Just post the output of
```bash
pgrep zscroll | xargs -I '{}' pstree -p -s "{}"
```
this will tell you.

I think because `zscroll` is running in the background, it's not properly termintated. What I would suggest is to use a `trap` to manually terminate all child processes when polybar tries to terminate the script. Use something like the script described at the end of [this](https://unix.stackexchange.com/a/55922/135052) stackexchange answer (you may need to also trap the `EXIT` signal in order for it to work)

**Comment by hshin23** [comment]
It's running as systemd's children.
I will look into using `trap`.
But I didn't know that the custom scripts run outside of polybar..

**Comment by patrick96** [comment]
Custom scripts run as direct children of polybar but I have noticed that if those scripts start background processes that don't terminate, those background processes don't get terminated properly once the script exits (is killed by polybar) and are just attached to the init process where they continue forever
