### ISSUE TITLE
Use two soundcards with one volume indicator in the bar

### ISSUE THREAD

**Issue by Spring80** [jaagr/polybar#837]
Hi, guys!

I use two soundcard there's my polybar config:

[module/volume]
type = internal/volume

master-soundcard = default
speaker-soundcard = hw:0
master-mixer = Master
speaker-mixer = PCM

If I use this configuration I have one volume indicator in the bar, but it does not match to the alsamixer (like 1% in the bar and ~15% in alsamixer and etc.). If I use two volume it's ok:

[module/volume]
type = internal/volume

master-soundcard = default
master-mixer = Master

[module/volume-2]
type = internal/volume

master-soundcard = default
master-mixer = PCM

How can I use two soundcards with one volume indicator in the bar?

**Comment by patrick96** [comment]
Try to set `mapped = true`, this should match the alsamixer values.
Also in the version where you use two modules you use the default soundcard for both. But in the one module version you use default and hw:0, maybe this could also be an issue

**Comment by Spring80** [comment]
If I use mapped = true in the bar always 0%. I also tried 
master-soundcard = hw:2
speaker-soundcard = hw:0 
the same (in the bar 12% and 100% in alsamixer).

**Comment by patrick96** [comment]
Having a closer look at this, I don't think what you want is possible. Polybar will always show the value for the speaker soundcard if possible and if the headphones are not plugged in. The module can also not switch dynamically between cards since it initializes the cards when the bar starts. You either have to use two separate modules or use the [`pavolume`](https://github.com/jaagr/polybar/wiki/User-contributed-modules#pulseaudio-volume) user-contributed module, if you use pulseaudio
