### ISSUE TITLE
Hang after executing command

### ISSUE THREAD

**Issue by koxu1996** [jaagr/polybar#853]
Hello,
I used example config, but power menu was not working at all. I expected some errors in console, but there were not any. After enabling trace level I see:
```
- bar: Received button press: 1 at pos(1662, 13)
- Found matching input area
* Uncaught input event, forwarding to shell... (input: sudo poweroff)
* Executing shell command: sudo poweroff
- command: Waiting for pid 1612 to finish...
- command: Stopped by signal 22
- command: Waiting for pid 1612 to finish...
```
and after that, polybar hang and I have to kill process with -9 option.

**Comment by patrick96** [comment]
That probably happens because if polybar executes `sudo poweroff`, the shell waits for the user to input the password, but since polybar executes the shell command in the background, `sudo` will never get the password and hangs. You'll either have to configure `sudo` to work w/o password (not recommended), use a graphical sudo like `gksudo` or the likes, or remove the `sudo` command entirely (most systems will allow you to run `poweroff` w/o root, if yours don't you'll have to look up how to enable that)

**Comment by koxu1996** [comment]
Is there any option to exec command without waiting for completion? And what about redirecting _stdout_ and _stderr_? It would be great to see command output and know what's going on.

**Comment by patrick96** [comment]
If you want polybar not to wait for completion and just run the command in the background, suffix the command with `&`

You can redirect the output of any command as you would with a normal shell command:
```bash
cmd > /path/to/logfile
```
I know this is not the best solution, but it's the only way to do this right now.
The issue is that the sudo password prompt is not written to `stdin` nor `stdout`, but directly to the terminal device, so this won't help you in this case.
