### ISSUE TITLE
Formatting leftpad not working properly

### ISSUE THREAD

**Issue by AUTplayed** [jaagr/polybar#891]
I have the cpu module in my bar with the label 
`label = %percentage:3:3%%`

and to my understanding it means min and max = 3, so it should always be width: 3

But if my cpu percentage changes from a 1-digit number to a 2-digit number the width increases..
![1digit](https://i.imgur.com/mZ9rwIl.png)
![2digit](https://i.imgur.com/mtL63Yl.png)

Am I misunderstanding the formatting or is there an issue here?
Thanks for your help in advance!

**Comment by patrick96** [comment]
Sorry for the delay.
I have looked at the images and the label with two digits is only 4 pixels wider than the one with one digit. I suspect you use a non-monospaced font, the min and max values make polybar insert extra whitespaces so that there are at least and at most three characters, but if your characters don't all have the same width the label will still change in size. Try to use a monospaced font and the problem should go away.

**Comment by AUTplayed** [comment]
Indeed, using a monospaced font fixed the issue. Thanks

**Comment by NBonaparte** [comment]
Not right now, but printf-style formatting is being considered: #1063
