### ISSUE TITLE
How can I add multiple menus?

### ISSUE THREAD

**Issue by mikelpint** [jaagr/polybar#907]
I cannot add multiple menus to polybar because if I have more than one only one gets openned.

**Comment by patrick96** [comment]
You can't. Currently you can only have a single menu module per bar, as is also noted on the [Wiki](https://github.com/jaagr/polybar/wiki/Module:-menu) (otherwise they'll interfere with each other).
I think this is because when the module sends the `menu-open-*` command, polybar can't tell to which menu it should send it, so you can only have a reliable menu, if you have at most one menu module, so polybar always sends the command to the right module.

**Comment by mikelpint** [comment]
OK. Thank you for the quick response.
