### ISSUE TITLE
polybar freezes frequently

### ISSUE THREAD

**Issue by rynnon** [jaagr/polybar#918]
Polybar freezes every other hour on my system - I can still click on it to switch workspaces, but the information shown is not updated at all. I've been running it in a screen session to look at error messages, and it put out the following (yes, it creates tabs for some reason; "wlx.." is my wifi interface):

>            warn: module/wlan: Failed to query interface 'wlx8416f91d1abc'     
> warn: module/wlan: Failed to query interface 'wlx8416f91d1abc'
> warn:  module/wlan: Failed to query interface 'wlx8416f91d1abc'

It might be of note that my wifi connection gets restarted often (maybe every 30 min), automatically. The driver apparently can't handle poor signal strength gracefully.

OS: Ubuntu 16.04
WM: i3
polybar -v: polybar 2.5.2
Features: +alsa -curl +i3 +mpd +network

polybar config: https://github.com/rynnon/dotfiles-i3/blob/i3-lubuntu/.config/polybar/config

**Comment by jaagr** [comment]
Update polybar.

**Comment by Geigerkind** [comment]
Hey @jaagr ,
I am experiencing the same issues with version 3.6.3. I initially thought that I had the same issue since I got the same warning, but even after removing the module the freezes persist. However for me I cant interact with polybar anymore. I cant see any error being output in the log files. Im using a multihead setup with multiple concurrent polybars.
