### ISSUE TITLE
Option to use legacy date

### ISSUE THREAD

**Issue by brianclinkenbeard** [jaagr/polybar#932]
The majority of dates and times (at least when separated by different modules with the same type) are not longer than 63 characters. It seems to me the ability to have non-padded dates offers greater benefit than having a 1024 character limit date with `std::put_time`.

**Comment by patrick96** [comment]
The change to `std::put_time` was made because of #744 which shows an actual use-case for longer than 63 character date strings. `std::put_time` doesn't actually have an upper character limit, it supports arbitrary length outputs. We will not add the ability to use both `strftime` and `std::put_time` within the date module, as this would make it too complex. If you really need non-padded tokens, use a script module with the `date` command.
